-- ═══════════════════════════════════════════════════════════════════════════
-- 0002 — Catalogos de dominio cerrado (esquema `ref`)
--
-- Anti-patron P9: como `VARCHAR` sin catalogo, «BINACIONAL» y «Binacional»
-- cuentan como dos categorias y el consolidado del RAO no cuadra. Todos los
-- dominios cerrados viven aqui.
--
-- ⚠️ TODO(JACID): PROMPT.md habla de «los 26 catalogos de `ref`». Ese numero
-- sale de `anexo_A_ddl_paid.sql`, que no existe. Los catalogos de este archivo
-- son los que las reglas R1–R19 exigen; el recuento no coincide
-- necesariamente. Si el DDL traia catalogos que ninguna regla nombra, aqui
-- faltan. Ver docs/DECISIONES.md, D-13.
--
-- Patron comun de un catalogo:
--   id           clave subrogada
--   codigo       clave natural estable, en MAYUSCULAS_CON_GUION_BAJO. Es la que
--                usan el codigo de la aplicacion y las semillas; el `id` puede
--                cambiar entre despliegues, el `codigo` no.
--   nombre       etiqueta para la interfaz, con tildes y enes
--   descripcion  texto de ayuda, opcional
--   orden        orden de presentacion en los desplegables
--   activo       baja logica de una entrada de catalogo (R14 en miniatura):
--                una entrada retirada debe seguir existiendo, porque hay filas
--                historicas que la referencian
-- ═══════════════════════════════════════════════════════════════════════════


-- ── ref.tipo_actividad ──
CREATE TABLE ref.tipo_actividad (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT tipo_actividad_codigo_unico UNIQUE (codigo),
  CONSTRAINT tipo_actividad_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.tipo_actividad IS 'Subtipos de ai.actividad. La disyuncion del subtipo se impone con clave foranea compuesta (P1).';

-- ── ref.tipo_asistencia ──
CREATE TABLE ref.tipo_asistencia (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT tipo_asistencia_codigo_unico UNIQUE (codigo),
  CONSTRAINT tipo_asistencia_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.tipo_asistencia IS 'R17: DIRECTA exige plan operacional.';

-- ── ref.plan_operacional ──
CREATE TABLE ref.plan_operacional (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT plan_operacional_codigo_unico UNIQUE (codigo),
  CONSTRAINT plan_operacional_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.plan_operacional IS 'R17: Plan San Roque II, Plan Renacer. TODO(JACID): listado vigente completo.';

-- ── ref.coami ──
CREATE TABLE ref.coami (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT coami_codigo_unico UNIQUE (codigo),
  CONSTRAINT coami_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.coami IS 'R18: los siete COAMI de la Reserva Naval. Relacion cero-a-muchos, ninguno por defecto.';

-- ── ref.categoria_adjunto ──
CREATE TABLE ref.categoria_adjunto (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT categoria_adjunto_codigo_unico UNIQUE (codigo),
  CONSTRAINT categoria_adjunto_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.categoria_adjunto IS 'R12: IMAGEN, DOCUMENTO, AUDIO, VIDEO.';

-- ── ref.fase_documental ──
CREATE TABLE ref.fase_documental (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT fase_documental_codigo_unico UNIQUE (codigo),
  CONSTRAINT fase_documental_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.fase_documental IS 'Fases 1, 2 y 3 de los soportes. TODO(JACID) Q7: que significa cada una.';

-- ── ref.estado_registro ──
CREATE TABLE ref.estado_registro (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT estado_registro_codigo_unico UNIQUE (codigo),
  CONSTRAINT estado_registro_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.estado_registro IS 'R14: el borrado es logico. ACTIVO, INACTIVO, ELIMINADO.';

-- ── ref.tipo_red ──
CREATE TABLE ref.tipo_red (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT tipo_red_codigo_unico UNIQUE (codigo),
  CONSTRAINT tipo_red_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.tipo_red IS 'R2: ADMINISTRACION, OPERACION, CONSULTA.';

-- ── ref.resultado_intento_autenticacion ──
CREATE TABLE ref.resultado_intento_autenticacion (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT resultado_intento_autenticacion_codigo_unico UNIQUE (codigo),
  CONSTRAINT resultado_intento_autenticacion_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.resultado_intento_autenticacion IS 'R4: ocho causas para el analisis forense. La pantalla siempre dice lo mismo.';

-- ── ref.nivel_jerarquia ──
CREATE TABLE ref.nivel_jerarquia (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT nivel_jerarquia_codigo_unico UNIQUE (codigo),
  CONSTRAINT nivel_jerarquia_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.nivel_jerarquia IS 'R6: Fuerza -> Componente -> Unidad Tactica.';

-- ── ref.ambito_visibilidad ──
CREATE TABLE ref.ambito_visibilidad (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT ambito_visibilidad_codigo_unico UNIQUE (codigo),
  CONSTRAINT ambito_visibilidad_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.ambito_visibilidad IS 'P4: seg.rol.ambito_visibilidad. Que alcance de datos concede un rol.';

-- ── ref.tipo_documento_identidad ──
CREATE TABLE ref.tipo_documento_identidad (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT tipo_documento_identidad_codigo_unico UNIQUE (codigo),
  CONSTRAINT tipo_documento_identidad_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.tipo_documento_identidad IS 'Mismo numero con distinto tipo coexiste; con el mismo tipo, no (Puerta 1).';

-- ── ref.escalafon ──
CREATE TABLE ref.escalafon (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT escalafon_codigo_unico UNIQUE (codigo),
  CONSTRAINT escalafon_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.escalafon IS 'Escalafones de la ARC. TODO(JACID): confirmar el listado oficial.';

-- ── ref.grado ──
CREATE TABLE ref.grado (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT grado_codigo_unico UNIQUE (codigo),
  CONSTRAINT grado_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.grado IS 'Grados militares. TODO(JACID): confirmar el listado oficial y su correspondencia con escalafon.';

-- ── ref.tipo_entidad ──
CREATE TABLE ref.tipo_entidad (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT tipo_entidad_codigo_unico UNIQUE (codigo),
  CONSTRAINT tipo_entidad_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.tipo_entidad IS 'Naturaleza de una entidad A.I.: publica, privada, ONG, cooperacion internacional...';

-- ── ref.tipo_herramienta_aid ──
CREATE TABLE ref.tipo_herramienta_aid (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT tipo_herramienta_aid_codigo_unico UNIQUE (codigo),
  CONSTRAINT tipo_herramienta_aid_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.tipo_herramienta_aid IS 'Los 11 tipos de herramienta AID. TODO(JACID) Q3: campos propios de cada tipo.';

-- ── ref.campana_institucional ──
CREATE TABLE ref.campana_institucional (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT campana_institucional_codigo_unico UNIQUE (codigo),
  CONSTRAINT campana_institucional_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.campana_institucional IS 'Las 17 campanas derivadas de COGFM. SE SIEMBRA VACIO: TODO(JACID) Q2. Inventar diecisiete nombres verosimiles contaminaria el RAO.';

-- ── ref.tipo_operacion ──
CREATE TABLE ref.tipo_operacion (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT tipo_operacion_codigo_unico UNIQUE (codigo),
  CONSTRAINT tipo_operacion_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.tipo_operacion IS 'Pestana Tipo Operacion. SE SIEMBRA VACIO: TODO(JACID) Q4, no se conoce el formulario real.';

-- ── ref.servicio_prestado ──
CREATE TABLE ref.servicio_prestado (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT servicio_prestado_codigo_unico UNIQUE (codigo),
  CONSTRAINT servicio_prestado_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.servicio_prestado IS 'Pestana Servicios Prestados. SE SIEMBRA VACIO: TODO(JACID) Q4.';

-- ── ref.grupo_poblacional ──
CREATE TABLE ref.grupo_poblacional (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT grupo_poblacional_codigo_unico UNIQUE (codigo),
  CONSTRAINT grupo_poblacional_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.grupo_poblacional IS 'Pestana Poblacion Beneficiada: desglose de la cifra que alimenta el RAO. SE SIEMBRA VACIO: TODO(JACID) Q4/Q10.';

-- ── ref.medio_difusion ──
CREATE TABLE ref.medio_difusion (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT medio_difusion_codigo_unico UNIQUE (codigo),
  CONSTRAINT medio_difusion_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.medio_difusion IS 'Pestana Medios Difusion. TODO(JACID): confirmar el listado.';

-- ── ref.medio_utilizado ──
CREATE TABLE ref.medio_utilizado (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT medio_utilizado_codigo_unico UNIQUE (codigo),
  CONSTRAINT medio_utilizado_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.medio_utilizado IS 'Pestana Medios Utilizados. TODO(JACID): confirmar el listado.';

-- ── ref.tipo_recurso ──
CREATE TABLE ref.tipo_recurso (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT tipo_recurso_codigo_unico UNIQUE (codigo),
  CONSTRAINT tipo_recurso_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.tipo_recurso IS 'Pestana Recursos Utilizados. TODO(JACID): confirmar el listado.';

-- ── ref.tipo_bien_donado ──
CREATE TABLE ref.tipo_bien_donado (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT tipo_bien_donado_codigo_unico UNIQUE (codigo),
  CONSTRAINT tipo_bien_donado_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.tipo_bien_donado IS 'Pestana Bienes Donados. TODO(JACID): confirmar el listado.';

-- ── ref.tipo_alianza ──
CREATE TABLE ref.tipo_alianza (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT tipo_alianza_codigo_unico UNIQUE (codigo),
  CONSTRAINT tipo_alianza_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.tipo_alianza IS 'R16: las unidades concretan alianzas; los convenios son de JACID.';

-- ── ref.tipo_normatividad ──
CREATE TABLE ref.tipo_normatividad (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT tipo_normatividad_codigo_unico UNIQUE (codigo),
  CONSTRAINT tipo_normatividad_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.tipo_normatividad IS 'R16: la normatividad solo la carga JACID; las unidades descargan.';

-- ── ref.estado_solicitud_eliminacion ──
CREATE TABLE ref.estado_solicitud_eliminacion (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT estado_solicitud_eliminacion_codigo_unico UNIQUE (codigo),
  CONSTRAINT estado_solicitud_eliminacion_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.estado_solicitud_eliminacion IS 'R14: PENDIENTE, APROBADA, RECHAZADA.';

-- ── ref.hemisferio ──
CREATE TABLE ref.hemisferio (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT hemisferio_codigo_unico UNIQUE (codigo),
  CONSTRAINT hemisferio_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.hemisferio IS 'R13: N, S para latitud; E, W para longitud. El signo decimal lo da el hemisferio.';

-- ── ref.tramo_avance ──
CREATE TABLE ref.tramo_avance (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT tramo_avance_codigo_unico UNIQUE (codigo),
  CONSTRAINT tramo_avance_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.tramo_avance IS 'R10: 10,20,30,40,50,60,70,100. NO existen 80 ni 90. Tambien como catalogo, para que un desplegable no pueda ofrecerlos.';


-- ═══ Catalogos con estructura propia ═══════════════════════════════════════

-- ── ref.departamento ──
-- P10: nada de `nombre_departamento` repetido por municipio. El municipio
-- apunta aqui con una clave foranea, y el nombre vive en un solo sitio.
CREATE TABLE ref.departamento (
  id             smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_dane    char(2) NOT NULL,
  nombre         varchar(120) NOT NULL,
  activo         boolean NOT NULL DEFAULT TRUE,
  creado_en      timestamptz NOT NULL DEFAULT now(),
  creado_por     bigint,
  modificado_en  timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT departamento_codigo_dane_unico UNIQUE (codigo_dane),
  CONSTRAINT departamento_codigo_dane_formato CHECK (codigo_dane ~ '^[0-9]{2}$')
);
COMMENT ON TABLE ref.departamento IS 'Division politico-administrativa DANE, nivel departamento.';

-- ── ref.municipio ──
CREATE TABLE ref.municipio (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_departamento  smallint NOT NULL REFERENCES ref.departamento(id),
  codigo_dane      char(5) NOT NULL,
  -- Los dos primeros digitos del codigo DANE de un municipio SON el codigo de
  -- su departamento. Se derivan en una columna generada y se atan al
  -- departamento con una clave foranea: asi es imposible colgar un municipio
  -- del departamento equivocado.
  --
  -- No es desnormalizar (P10): la columna no se digita ni se puede escribir,
  -- se calcula del propio codigo. Lo que estaria prohibido es guardar
  -- `nombre_departamento` repetido por municipio, y eso no ocurre aqui.
  codigo_dane_departamento char(2) GENERATED ALWAYS AS (substring(codigo_dane FROM 1 FOR 2)) STORED,
  nombre           varchar(120) NOT NULL,
  activo           boolean NOT NULL DEFAULT TRUE,
  creado_en        timestamptz NOT NULL DEFAULT now(),
  creado_por       bigint,
  modificado_en    timestamptz NOT NULL DEFAULT now(),
  modificado_por   bigint,
  CONSTRAINT municipio_codigo_dane_unico UNIQUE (codigo_dane),
  CONSTRAINT municipio_codigo_dane_formato CHECK (codigo_dane ~ '^[0-9]{5}$'),
  CONSTRAINT municipio_codigo_coherente_con_departamento
    FOREIGN KEY (codigo_dane_departamento) REFERENCES ref.departamento(codigo_dane)
);
COMMENT ON TABLE ref.municipio IS
  'Division politico-administrativa DANE, nivel municipio. SE SIEMBRA VACIO: la lista oficial (DIVIPOLA) son mas de 1100 filas y se carga del archivo del DANE, no se teclea. Una lista parcial es peor que una vacia porque parece completa.';

-- ── ref.extension_permitida ──
-- R12. La extension no es la verdad: el MIME real manda. Esta tabla guarda
-- las dos cosas para poder contrastarlas.
CREATE TABLE ref.extension_permitida (
  id                   smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_categoria_adjunto smallint NOT NULL REFERENCES ref.categoria_adjunto(id),
  extension            varchar(10) NOT NULL,
  mimes_esperados      text[] NOT NULL,
  activo               boolean NOT NULL DEFAULT TRUE,
  creado_en            timestamptz NOT NULL DEFAULT now(),
  creado_por           bigint,
  modificado_en        timestamptz NOT NULL DEFAULT now(),
  modificado_por       bigint,
  CONSTRAINT extension_permitida_unica UNIQUE (extension),
  CONSTRAINT extension_permitida_minuscula CHECK (extension = lower(extension)),
  CONSTRAINT extension_permitida_con_mimes CHECK (cardinality(mimes_esperados) > 0)
);
COMMENT ON TABLE ref.extension_permitida IS
  'R12: extensiones por categoria y el MIME real que cada una debe presentar. Se valida contra el contenido, no contra el nombre del archivo.';

-- ── ref.atributo_herramienta_aid ──
CREATE TABLE ref.atributo_herramienta_aid (
  id                       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tipo_herramienta_aid  smallint NOT NULL REFERENCES ref.tipo_herramienta_aid(id),
  codigo                   varchar(60) NOT NULL,
  nombre                   varchar(200) NOT NULL,
  tipo_dato                varchar(20) NOT NULL,
  obligatorio              boolean NOT NULL DEFAULT FALSE,
  orden                    smallint NOT NULL DEFAULT 0,
  activo                   boolean NOT NULL DEFAULT TRUE,
  creado_en                timestamptz NOT NULL DEFAULT now(),
  creado_por               bigint,
  modificado_en            timestamptz NOT NULL DEFAULT now(),
  modificado_por           bigint,
  CONSTRAINT atributo_herramienta_unico UNIQUE (id_tipo_herramienta_aid, codigo),
  CONSTRAINT atributo_herramienta_tipo_dato_valido
    CHECK (tipo_dato IN ('TEXTO', 'ENTERO', 'DECIMAL', 'FECHA', 'BOOLEANO', 'CATALOGO'))
);
COMMENT ON TABLE ref.atributo_herramienta_aid IS
  'Campos adicionales que se activan por cada tipo de herramienta AID. SE SIEMBRA VACIO: TODO(JACID) Q3.';

-- ═══ Valores estructurales ═════════════════════════════════════════════════
--
-- Estos NO son semillas: son estructura. La funcion `ref.id_estado_activo()`
-- de la migracion 0009 busca el estado por el codigo 'ACTIVO', y los
-- disparadores de cuota (R11) y de `registro_completo` (R19) dependen de ella.
-- Si estas filas vivieran en el script de semillas, una base migrada pero sin
-- sembrar tendria disparadores que no fallan y no cuentan: el peor de los dos
-- mundos.
--
-- El resto de los catalogos —geografia DANE, COAMI, grados, extensiones— si
-- son semillas y viven en `pnpm db:seed`.
INSERT INTO ref.estado_registro (id, codigo, nombre, descripcion, orden)
OVERRIDING SYSTEM VALUE VALUES
  (1, 'ACTIVO',    'Activo',    'Registro vigente.', 1),
  (2, 'INACTIVO',  'Inactivo',  'Registro dado de baja, visible en consultas historicas.', 2),
  (3, 'ELIMINADO', 'Eliminado', 'Borrado logico aprobado por JACID (R14). No aparece en consultas ordinarias.', 3);

-- ── Privilegios de `ref` ───────────────────────────────────────────────────
-- Los catalogos los lee todo el mundo; solo administracion los modifica. Un
-- operador que pueda anadir una entrada de catalogo reintroduce P9 por la
-- puerta de atras: dos entradas para la misma cosa.
GRANT SELECT ON ALL TABLES IN SCHEMA ref TO paid_consulta, paid_operacion, paid_administracion;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA ref TO paid_administracion;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA ref TO paid_administracion;
