-- ═══════════════════════════════════════════════════════════════════════════
-- 0003 — Estructura organizacional (esquema `org`)
--
-- R6: Fuerza -> Componente -> Unidad Tactica. Una unidad ve lo suyo y lo de
-- sus subordinadas, nunca lo de sus pares.
--
-- Anti-patron P10: nada de `fuerza` ni `componente` como texto por unidad. Hay
-- UNA tabla de unidades con referencia a si misma, y el nivel sale del
-- catalogo `ref.nivel_jerarquia`. La jerarquia completa se expresa con una
-- `ruta_jerarquica` de tipo `ltree`, que es sobre la que operan las politicas
-- RLS de la migracion 0010.
--
-- ⚠️ TODO(JACID): esquema derivado de PROMPT.md. Ver docs/DECISIONES.md, D-13.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE org.unidad (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo              varchar(30) NOT NULL,
  sigla               varchar(30) NOT NULL,
  nombre              varchar(250) NOT NULL,
  id_nivel_jerarquia  smallint NOT NULL REFERENCES ref.nivel_jerarquia(id),
  id_unidad_superior  bigint REFERENCES org.unidad(id),

  -- Derivada de `id_unidad_superior` por disparador (ver 0009). No se digita.
  -- Es la columna sobre la que RLS decide que ve cada unidad, asi que si se
  -- pudiera escribir a mano, RLS seria opinable.
  ruta_jerarquica     ltree NOT NULL,

  id_municipio        integer REFERENCES ref.municipio(id),

  -- R14: borrado logico.
  id_estado_registro  smallint NOT NULL REFERENCES ref.estado_registro(id),

  -- P3: las cuatro columnas de auditoria de fila, que guardan el ULTIMO
  -- modificador, MAS la bitacora de R15. Las dos cosas, no una.
  creado_en           timestamptz NOT NULL DEFAULT now(),
  creado_por          bigint,
  modificado_en       timestamptz NOT NULL DEFAULT now(),
  modificado_por      bigint,

  CONSTRAINT unidad_codigo_unico UNIQUE (codigo),
  CONSTRAINT unidad_sigla_unica UNIQUE (sigla),
  -- La sigla alimenta la credencial `<SIGLA_UNIDAD>_PAID` de R5, asi que tiene
  -- que ser un identificador limpio: si admitiera espacios o tildes, la
  -- credencial derivada no cumpliria su propio patron.
  CONSTRAINT unidad_sigla_formato CHECK (sigla ~ '^[A-Z0-9]{2,20}$'),
  -- Una unidad no puede ser su propia superior. No cubre ciclos mas largos;
  -- de eso se encarga el disparador de la ruta jerarquica, que detecta el
  -- ciclo al intentar construir la ruta.
  CONSTRAINT unidad_no_es_su_propia_superior CHECK (id_unidad_superior IS DISTINCT FROM id)
);

COMMENT ON TABLE org.unidad IS
  'Unidades de la ARC en una sola tabla con referencia a si misma (P10). La jerarquia vive en ruta_jerarquica (ltree) y es la base de RLS (R6). TODO(JACID): derivado de PROMPT.md.';
COMMENT ON COLUMN org.unidad.ruta_jerarquica IS
  'DERIVADA por disparador desde id_unidad_superior. No escribir a mano: es la columna sobre la que RLS decide la visibilidad.';
COMMENT ON COLUMN org.unidad.sigla IS
  'Alimenta la credencial <SIGLA_UNIDAD>_PAID de R5. De ahi el formato restringido.';

-- ── Privilegios ────────────────────────────────────────────────────────────
-- R14: `DELETE` NO se concede a paid_operacion. Solo administracion.
GRANT SELECT ON org.unidad TO paid_consulta, paid_operacion, paid_administracion;
GRANT INSERT, UPDATE ON org.unidad TO paid_operacion, paid_administracion;
GRANT DELETE ON org.unidad TO paid_administracion;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA org TO paid_operacion, paid_administracion;
