-- ═══════════════════════════════════════════════════════════════════════════
-- 0004 — Seguridad (esquema `seg`)
--
-- Cubre R1 (sesion de 10 min), R2 (red cerrada), R3 (captcha de un solo uso),
-- R4 (ocho causas en base, un mensaje en pantalla), R5 (credencial de unidad),
-- R14 (solicitud de eliminacion) y R16 (atribuciones de JACID).
--
-- Anti-patrones que este archivo evita a proposito:
--   P4 — RBAC de verdad: `seg.permiso` con la tripleta modulo/submodulo/accion,
--        `seg.rol_permiso`, `seg.usuario_rol` con vigencia y
--        `seg.rol.id_ambito_visibilidad`. Un campo `id_rol` no es control de
--        acceso basado en roles.
--   P7 — Del testigo de sesion se guarda el RESUMEN, no el testigo. Una lectura
--        de la base no puede equivaler a suplantar una sesion activa.
--
-- ⚠️ TODO(JACID): esquema derivado de PROMPT.md. Ver docs/DECISIONES.md, D-13.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── R2 — Redes autorizadas ─────────────────────────────────────────────────
--
-- Viven en la base, NO en variables de entorno ni en el codigo: el manual
-- advierte que el direccionamiento IP esta «pendiente» y JACID debe poder
-- cambiarlo sin desplegar.
CREATE TABLE seg.red_autorizada (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rango          cidr NOT NULL,
  id_tipo_red    smallint NOT NULL REFERENCES ref.tipo_red(id),
  descripcion    varchar(250) NOT NULL,
  activo         boolean NOT NULL DEFAULT TRUE,
  vigente_desde  timestamptz NOT NULL DEFAULT now(),
  vigente_hasta  timestamptz,
  creado_en      timestamptz NOT NULL DEFAULT now(),
  creado_por     bigint,
  modificado_en  timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT red_autorizada_rango_unico UNIQUE (rango),
  CONSTRAINT red_autorizada_vigencia_coherente
    CHECK (vigente_hasta IS NULL OR vigente_hasta > vigente_desde)
);
COMMENT ON TABLE seg.red_autorizada IS
  'R2: rangos desde los que procede la autenticacion. En la base y no en el entorno, para que JACID los cambie sin desplegar. TODO(JACID) Q5: rangos definitivos de la Intranet ARC.';

-- ── P4 — Permisos, roles y su asignacion ───────────────────────────────────
CREATE TABLE seg.permiso (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modulo      varchar(40) NOT NULL,
  submodulo   varchar(40),
  accion      varchar(40) NOT NULL,
  -- Se deriva de la tripleta, no se digita: asi `ALIANZA.AVANCE` no puede
  -- existir con dos escrituras distintas.
  codigo      varchar(130) GENERATED ALWAYS AS (
                modulo || COALESCE('.' || submodulo, '') || '.' || accion
              ) STORED,
  descripcion varchar(250) NOT NULL,
  creado_en   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT permiso_tripleta_unica UNIQUE (modulo, submodulo, accion),
  CONSTRAINT permiso_modulo_formato CHECK (modulo ~ '^[A-Z0-9_]+$'),
  CONSTRAINT permiso_submodulo_formato CHECK (submodulo IS NULL OR submodulo ~ '^[A-Z0-9_]+$'),
  CONSTRAINT permiso_accion_formato CHECK (accion ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE seg.permiso IS 'P4: la tripleta modulo/submodulo/accion. El codigo se deriva, no se teclea.';

CREATE TABLE seg.rol (
  id                    smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo                varchar(40) NOT NULL,
  nombre                varchar(120) NOT NULL,
  descripcion           varchar(250),
  -- P4: el ambito de visibilidad es parte del rol, no una consecuencia
  -- implicita de su nombre.
  id_ambito_visibilidad smallint NOT NULL REFERENCES ref.ambito_visibilidad(id),
  activo                boolean NOT NULL DEFAULT TRUE,
  creado_en             timestamptz NOT NULL DEFAULT now(),
  creado_por            bigint,
  modificado_en         timestamptz NOT NULL DEFAULT now(),
  modificado_por        bigint,
  CONSTRAINT rol_codigo_unico UNIQUE (codigo),
  CONSTRAINT rol_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);

CREATE TABLE seg.rol_permiso (
  id_rol     smallint NOT NULL REFERENCES seg.rol(id) ON DELETE CASCADE,
  id_permiso integer NOT NULL REFERENCES seg.permiso(id) ON DELETE CASCADE,
  creado_en  timestamptz NOT NULL DEFAULT now(),
  creado_por bigint,
  PRIMARY KEY (id_rol, id_permiso)
);

-- ── R5 — Credencial de unidad, no de persona ───────────────────────────────
CREATE TABLE seg.usuario (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  credencial          varchar(30) NOT NULL,
  -- Argon2id. El prefijo del formato PHC (`$argon2id$`) se comprueba, para que
  -- un hash de otro algoritmo (o una clave en claro) no entre por descuido.
  hash_clave          text NOT NULL,
  id_unidad           bigint NOT NULL REFERENCES org.unidad(id),
  -- R5: vincula OPCIONALMENTE la credencial a un tripulante. La clave foranea
  -- a ai.personal se agrega en 0005, cuando esa tabla existe.
  id_personal         bigint,

  activo              boolean NOT NULL DEFAULT TRUE,
  bloqueado_en        timestamptz,
  intentos_fallidos   smallint NOT NULL DEFAULT 0,
  clave_cambiada_en   timestamptz NOT NULL DEFAULT now(),
  clave_expira_en     timestamptz,
  ultimo_ingreso_en   timestamptz,

  id_estado_registro  smallint NOT NULL REFERENCES ref.estado_registro(id),
  creado_en           timestamptz NOT NULL DEFAULT now(),
  creado_por          bigint,
  modificado_en       timestamptz NOT NULL DEFAULT now(),
  modificado_por      bigint,

  CONSTRAINT usuario_credencial_unica UNIQUE (credencial),
  -- R5: convencion <SIGLA_UNIDAD>_PAID en mayusculas.
  CONSTRAINT usuario_credencial_formato CHECK (credencial ~ '^[A-Z0-9]{2,20}_PAID$'),
  CONSTRAINT usuario_hash_clave_es_argon2id CHECK (hash_clave LIKE '$argon2id$%'),
  CONSTRAINT usuario_intentos_no_negativos CHECK (intentos_fallidos >= 0)
);
COMMENT ON TABLE seg.usuario IS
  'R5: usuarios de unidad, no de persona. BIM23_PAID, COOPCM_PAID, FNP_PAID, ADMIN_PAID, FUNCIONAL_PAID.';
COMMENT ON COLUMN seg.usuario.hash_clave IS
  'Argon2id en formato PHC. El CHECK del prefijo impide que entre una clave en claro o un hash de otro algoritmo.';

-- ── P4 — Asignacion de roles CON VIGENCIA ──────────────────────────────────
CREATE TABLE seg.usuario_rol (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario    bigint NOT NULL REFERENCES seg.usuario(id) ON DELETE CASCADE,
  id_rol        smallint NOT NULL REFERENCES seg.rol(id),
  vigente_desde timestamptz NOT NULL DEFAULT now(),
  vigente_hasta timestamptz,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  CONSTRAINT usuario_rol_vigencia_coherente
    CHECK (vigente_hasta IS NULL OR vigente_hasta > vigente_desde)
);
COMMENT ON TABLE seg.usuario_rol IS
  'P4: la asignacion tiene vigencia. Revocar un rol no es borrar la fila: es cerrar su vigencia, y asi queda el rastro de quien tuvo que permiso y cuando.';

-- Un usuario no puede tener el mismo rol dos veces a la vez. El indice parcial
-- cubre la asignacion abierta, que es la que importa.
CREATE UNIQUE INDEX usuario_rol_unico_vigente
  ON seg.usuario_rol (id_usuario, id_rol)
  WHERE vigente_hasta IS NULL;

-- ── Fase 2 — Historial de las ultimas 5 claves ─────────────────────────────
CREATE TABLE seg.historial_clave (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario bigint NOT NULL REFERENCES seg.usuario(id) ON DELETE CASCADE,
  hash_clave text NOT NULL,
  creado_en  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT historial_clave_es_argon2id CHECK (hash_clave LIKE '$argon2id$%')
);
COMMENT ON TABLE seg.historial_clave IS
  'Las ultimas 5 claves, para impedir reutilizarlas. La poda a 5 la hace la aplicacion en la Fase 2.';

-- ── R3 — Captcha de un solo uso ────────────────────────────────────────────
CREATE TABLE seg.captcha (
  id           uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  -- Se guarda el RESUMEN del reto, no el texto. Igual que con la clave: una
  -- lectura de la base no debe permitir resolver un captcha pendiente.
  hash_reto    char(64) NOT NULL,
  creado_en    timestamptz NOT NULL DEFAULT now(),
  -- Caduca a los 5 minutos. Derivado, no digitado: asi nadie emite un captcha
  -- con una hora de validez.
  --
  -- NO es una columna generada porque `timestamptz + interval` no es
  -- inmutable en PostgreSQL y el motor lo rechaza. Se deriva con el
  -- disparador `seg.fijar_expiracion_captcha` de mas abajo, que la sobreescribe
  -- siempre: el efecto practico es el mismo, no se puede digitar.
  expira_en    timestamptz NOT NULL DEFAULT now(),
  -- R3: se marca consumido al validarse CON INDEPENDENCIA DEL RESULTADO. Si
  -- solo se marcara al acertar, el mismo reto admitiria intentos infinitos.
  consumido_en timestamptz,
  direccion_ip inet,
  CONSTRAINT captcha_hash_es_sha256_hex CHECK (hash_reto ~ '^[0-9a-f]{64}$')
);
COMMENT ON TABLE seg.captcha IS
  'R3: un solo uso, caduca a los 5 minutos, y se marca consumido al validarse gane o pierda. Se guarda el resumen del reto, no el reto.';

-- ── R4 — Intentos de autenticacion: ocho causas ────────────────────────────
CREATE TABLE seg.intento_autenticacion (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  credencial_intentada varchar(60) NOT NULL,
  -- Aqui viven las ocho causas. En la pantalla, siempre «Credenciales
  -- invalidas». La distincion es para el analisis forense, no para el usuario.
  id_resultado         smallint NOT NULL REFERENCES ref.resultado_intento_autenticacion(id),
  id_usuario           bigint REFERENCES seg.usuario(id),
  direccion_ip         inet NOT NULL,
  agente_usuario       text,
  id_captcha           uuid REFERENCES seg.captcha(id),
  instante             timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE seg.intento_autenticacion IS
  'R4: ocho resultados posibles para el analisis forense. La interfaz nunca los distingue.';

-- ── R1 / P7 — Sesiones ─────────────────────────────────────────────────────
CREATE TABLE seg.sesion (
  id                  uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  id_usuario          bigint NOT NULL REFERENCES seg.usuario(id),
  id_unidad           bigint NOT NULL REFERENCES org.unidad(id),

  -- P7: el RESUMEN del testigo, nunca el testigo. El CHECK de formato sha256
  -- hex es lo que hace que un testigo en claro no quepa aqui por accidente.
  hash_testigo        char(64) NOT NULL,

  creada_en           timestamptz NOT NULL DEFAULT now(),
  -- R1: expiracion DESLIZANTE. Cada peticion autenticada desplaza
  -- `ultima_actividad_en`, y `expira_en` se recalcula sola porque es derivada.
  -- Redis lleva el TTL vivo; esta tabla es el registro durable.
  ultima_actividad_en timestamptz NOT NULL DEFAULT now(),
  -- Derivada por disparador, no generada: `timestamptz + interval` no es
  -- inmutable y PostgreSQL no admite columnas generadas con ella. El
  -- disparador la sobreescribe en cada INSERT y en cada UPDATE, asi que sigue
  -- siendo imposible fijarla a mano y la expiracion sigue siendo deslizante
  -- por construccion.
  expira_en           timestamptz NOT NULL DEFAULT now(),
  cerrada_en          timestamptz,
  motivo_cierre       varchar(30),
  direccion_ip        inet NOT NULL,
  agente_usuario      text,

  CONSTRAINT sesion_hash_testigo_unico UNIQUE (hash_testigo),
  CONSTRAINT sesion_hash_es_sha256_hex CHECK (hash_testigo ~ '^[0-9a-f]{64}$'),
  CONSTRAINT sesion_motivo_cierre_valido CHECK (
    motivo_cierre IS NULL OR motivo_cierre IN (
      'CIERRE_USUARIO', 'INACTIVIDAD', 'EXPIRACION', 'REVOCADA_ADMIN',
      'CLAVE_CAMBIADA', 'RED_NO_AUTORIZADA'
    )
  ),
  -- Una sesion cerrada tiene motivo, y una con motivo esta cerrada. Sin esto
  -- aparecen sesiones «cerradas sin saber por que», que es justo lo que R1
  -- quiere conservar.
  CONSTRAINT sesion_cierre_con_motivo CHECK (
    (cerrada_en IS NULL AND motivo_cierre IS NULL)
    OR (cerrada_en IS NOT NULL AND motivo_cierre IS NOT NULL)
  )
);
COMMENT ON TABLE seg.sesion IS
  'R1: 10 minutos de inactividad, expiracion deslizante evaluada en servidor. Redis lleva el TTL; esta tabla es el registro durable con el motivo de cierre.';
COMMENT ON COLUMN seg.sesion.hash_testigo IS
  'P7: resumen SHA-256 del testigo. El testigo en claro NO existe en la base. El CHECK de formato lo impide materialmente.';
COMMENT ON COLUMN seg.sesion.expira_en IS
  'DERIVADA de ultima_actividad_en por disparador. Deslizante por construccion: al desplazar la ultima actividad, la expiracion se mueve sola. No se digita: el disparador la sobreescribe.';

-- ── Disparadores de derivacion de expiracion ───────────────────────────────
--
-- Van aqui, con sus tablas, y no en 0009 (disparadores de dominio): son
-- derivaciones locales de estas dos tablas, y asi la migracion 0004 se aplica
-- y se revierte por si sola.

CREATE OR REPLACE FUNCTION seg.fijar_expiracion_captcha()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  -- R3: cinco minutos, siempre. Se ignora lo que traiga la sentencia.
  NEW.expira_en := NEW.creado_en + interval '5 minutes';
  RETURN NEW;
END
$$;

CREATE TRIGGER captcha_fijar_expiracion
  BEFORE INSERT OR UPDATE ON seg.captcha
  FOR EACH ROW EXECUTE FUNCTION seg.fijar_expiracion_captcha();

CREATE OR REPLACE FUNCTION seg.fijar_expiracion_sesion()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  -- R1: diez minutos desde la ultima actividad, siempre. Se ignora lo que
  -- traiga la sentencia, que es lo que hace la expiracion inmanipulable desde
  -- el cliente.
  NEW.expira_en := NEW.ultima_actividad_en + interval '10 minutes';
  RETURN NEW;
END
$$;

CREATE TRIGGER sesion_fijar_expiracion
  BEFORE INSERT OR UPDATE ON seg.sesion
  FOR EACH ROW EXECUTE FUNCTION seg.fijar_expiracion_sesion();

-- ── R14 — Eliminar es un tramite, no un boton ──────────────────────────────
CREATE TABLE seg.solicitud_eliminacion (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Que registro se quiere eliminar. Es una referencia generica a proposito:
  -- no es P1, porque esto no es una relacion de dominio sino una bitacora de
  -- tramite. Aun asi se acota a un esquema y tabla conocidos, y la aplicacion
  -- comprueba la existencia antes de crear la solicitud.
  esquema_objetivo   varchar(20) NOT NULL,
  tabla_objetivo     varchar(60) NOT NULL,
  id_registro        bigint NOT NULL,

  id_solicitante     bigint NOT NULL REFERENCES seg.usuario(id),
  -- El manual: «para eliminar se debe elevar la solicitud a JACID explicando
  -- los motivos». El motivo es obligatorio y no puede estar en blanco.
  motivo             text NOT NULL,
  solicitado_en      timestamptz NOT NULL DEFAULT now(),

  id_estado          smallint NOT NULL REFERENCES ref.estado_solicitud_eliminacion(id),
  id_decisor         bigint REFERENCES seg.usuario(id),
  resolucion         text,
  resuelto_en        timestamptz,

  CONSTRAINT solicitud_motivo_no_vacio CHECK (btrim(motivo) <> ''),
  CONSTRAINT solicitud_esquema_valido CHECK (esquema_objetivo IN ('ai', 'org', 'doc')),
  -- Resuelta significa: con decisor, con resolucion y con fecha. Las tres o
  -- ninguna.
  CONSTRAINT solicitud_resolucion_completa CHECK (
    (resuelto_en IS NULL AND id_decisor IS NULL AND resolucion IS NULL)
    OR (resuelto_en IS NOT NULL AND id_decisor IS NOT NULL AND btrim(resolucion) <> '')
  ),
  -- Nadie resuelve su propia solicitud.
  CONSTRAINT solicitud_decisor_distinto_del_solicitante
    CHECK (id_decisor IS NULL OR id_decisor <> id_solicitante)
);
COMMENT ON TABLE seg.solicitud_eliminacion IS
  'R14: solicitante, motivo obligatorio, decisor y resolucion. Sin esta tabla, lo unico que impide el DELETE es una frase (P8).';

-- ── Privilegios ────────────────────────────────────────────────────────────
GRANT SELECT ON ALL TABLES IN SCHEMA seg TO paid_consulta, paid_operacion, paid_administracion;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA seg TO paid_operacion, paid_administracion;
GRANT DELETE ON ALL TABLES IN SCHEMA seg TO paid_administracion;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA seg TO paid_operacion, paid_administracion;

-- Un operador no reparte permisos ni se da roles a si mismo: eso es
-- administracion. Sin esta revocacion, R16 (atribuciones centralizadas en
-- JACID) se puede sortear desde la propia aplicacion.
REVOKE INSERT, UPDATE ON seg.rol, seg.permiso, seg.rol_permiso, seg.usuario_rol, seg.red_autorizada
  FROM paid_operacion;
