-- ═══════════════════════════════════════════════════════════════════════════
-- 0005 — Los tres maestros de precedencia (esquema `ai`)
--
-- R8: antes de registrar CUALQUIER actividad deben existir Personal, Entidades
-- A.I. y Herramientas AID. Se impone con claves foraneas obligatorias desde
-- las actividades (migracion 0006), y la interfaz lo explica cuando el
-- catalogo esta vacio.
--
-- ⚠️ TODO(JACID): esquema derivado de PROMPT.md. Ver docs/DECISIONES.md, D-13.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Maestro 1 — ai.personal ────────────────────────────────────────────────
CREATE TABLE ai.personal (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tipo_documento_identidad smallint NOT NULL REFERENCES ref.tipo_documento_identidad(id),
  numero_documento            varchar(30) NOT NULL,
  nombres                     varchar(150) NOT NULL,
  apellidos                   varchar(150) NOT NULL,
  id_grado                    smallint REFERENCES ref.grado(id),
  id_escalafon                smallint REFERENCES ref.escalafon(id),
  id_unidad                   bigint NOT NULL REFERENCES org.unidad(id),
  correo                      varchar(150),
  telefono                    varchar(30),
  id_estado_registro          smallint NOT NULL REFERENCES ref.estado_registro(id),
  -- P3: las cuatro columnas de auditoria de fila MAS la bitacora de R15.
  creado_en           timestamptz NOT NULL DEFAULT now(),
  creado_por          bigint,
  modificado_en       timestamptz NOT NULL DEFAULT now(),
  modificado_por      bigint,

  -- Puerta 1: «Mismo numero de documento con distinto tipo coexiste; con el
  -- mismo tipo, no». Una cedula 123 y un pasaporte 123 son dos personas
  -- distintas; dos cedulas 123 son un error de digitacion.
  CONSTRAINT personal_documento_unico UNIQUE (id_tipo_documento_identidad, numero_documento),
  CONSTRAINT personal_numero_documento_no_vacio CHECK (btrim(numero_documento) <> ''),
  CONSTRAINT personal_nombres_no_vacios CHECK (btrim(nombres) <> ''),
  CONSTRAINT personal_apellidos_no_vacios CHECK (btrim(apellidos) <> '')
);
COMMENT ON TABLE ai.personal IS
  'R8, maestro 1 de 3. Tripulantes. UNIQUE por (tipo, numero) de documento: el mismo numero con distinto tipo coexiste.';

-- R5: ahora que ai.personal existe, se ata la credencial opcionalmente a un
-- tripulante. Se declara aqui y no en 0004 por el orden de creacion.
ALTER TABLE seg.usuario
  ADD CONSTRAINT usuario_personal_fk FOREIGN KEY (id_personal) REFERENCES ai.personal(id);
COMMENT ON COLUMN seg.usuario.id_personal IS
  'R5: vincula OPCIONALMENTE la credencial de unidad a un tripulante. La credencial sigue siendo de la unidad, no de la persona.';

-- ── Maestro 2 — ai.entidad ─────────────────────────────────────────────────
CREATE TABLE ai.entidad (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tipo_entidad     smallint NOT NULL REFERENCES ref.tipo_entidad(id),
  nit                 varchar(20),
  nombre              varchar(250) NOT NULL,

  -- Generada con la MISMA funcion que usa el cliente (ref.normalizar_texto,
  -- espejo de normalizarTexto() en packages/schema). Sobre esta columna va el
  -- indice GIN con pg_trgm de la migracion 0011, y es la base de la
  -- deduplicacion: si se pudiera digitar, dos filas «iguales» podrian tener
  -- normalizaciones distintas y el indice no las acercaria.
  nombre_normalizado  varchar(250) GENERATED ALWAYS AS (ref.normalizar_texto(nombre)) STORED,

  -- La unidad que registro la entidad. Es lo que hace que R6 y IA8 sean
  -- verificables sobre este maestro: sin una unidad, una consulta por
  -- similitud semantica (U3, Fase 6) podria devolver entidades que el ambito
  -- del usuario no alcanza, y la Puerta 6 comprueba justo lo contrario.
  id_unidad           bigint NOT NULL REFERENCES org.unidad(id),
  id_municipio        integer REFERENCES ref.municipio(id),
  direccion           varchar(250),
  telefono            varchar(30),
  correo              varchar(150),
  contacto            varchar(150),
  id_estado_registro  smallint NOT NULL REFERENCES ref.estado_registro(id),
  -- P3: las cuatro columnas de auditoria de fila MAS la bitacora de R15.
  creado_en           timestamptz NOT NULL DEFAULT now(),
  creado_por          bigint,
  modificado_en       timestamptz NOT NULL DEFAULT now(),
  modificado_por      bigint,

  CONSTRAINT entidad_nombre_no_vacio CHECK (btrim(nombre) <> ''),
  -- El NIT es unico cuando existe. No es obligatorio: hay entidades sin NIT
  -- (juntas de accion comunal, organizaciones de hecho) y exigirlo empujaria
  -- a inventarlo.
  CONSTRAINT entidad_nit_unico UNIQUE (nit)
);
COMMENT ON TABLE ai.entidad IS
  'R8, maestro 2 de 3. Entidades de Accion Integral. nombre_normalizado es generado y sostiene la deduplicacion (trigram en 0011, embeddings en la Fase 6).';
COMMENT ON COLUMN ai.entidad.nombre_normalizado IS
  'GENERADA con ref.normalizar_texto. Espejo exacto de normalizarTexto() en packages/schema: si divergen, aparecen duplicados que la interfaz dijo que no existian.';

-- ── Maestro 3 — ai.herramienta_aid ─────────────────────────────────────────
--
-- R13: la herramienta AID es uno de los SEIS formularios que capturan
-- georreferenciacion, y es el que se olvida, porque no es una actividad.
CREATE TABLE ai.herramienta_aid (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tipo_herramienta_aid smallint NOT NULL REFERENCES ref.tipo_herramienta_aid(id),
  codigo                  varchar(40) NOT NULL,
  nombre                  varchar(250) NOT NULL,
  descripcion             text,
  id_unidad               bigint NOT NULL REFERENCES org.unidad(id),
  id_municipio            integer REFERENCES ref.municipio(id),
  fecha_registro          date NOT NULL,
  id_estado_registro      smallint NOT NULL REFERENCES ref.estado_registro(id),
  -- ═══ R13 — Georreferenciacion ═══════════════════════════════════════════
  -- Se almacenan los OCHO componentes GMS tal como los digita el usuario.
  latitud_grados      smallint NOT NULL,
  latitud_minutos     smallint NOT NULL,
  latitud_segundos    numeric(8,5) NOT NULL,
  latitud_hemisferio  char(1) NOT NULL,
  longitud_grados     smallint NOT NULL,
  longitud_minutos    smallint NOT NULL,
  longitud_segundos   numeric(8,5) NOT NULL,
  longitud_hemisferio char(1) NOT NULL,

  -- Las decimales son COLUMNAS GENERADAS: no se escriben, se derivan, y por
  -- eso no pueden divergir de las GMS (anti-patron P6). Un punto equivocado es
  -- peor que uno ausente, porque parece plausible.
  --
  -- Esta expresion es el espejo exacto de `aDecimal()` en
  -- packages/schema/src/coordenadas.ts. Una prueba de la Puerta 1 compara
  -- ambas sobre el mismo conjunto de coordenadas.
  latitud_decimal     numeric(9,6) GENERATED ALWAYS AS (
                        (latitud_grados + latitud_minutos / 60.0 + latitud_segundos / 3600.0)
                        * CASE latitud_hemisferio WHEN 'S' THEN -1 ELSE 1 END
                      ) STORED,
  longitud_decimal    numeric(9,6) GENERATED ALWAYS AS (
                        (longitud_grados + longitud_minutos / 60.0 + longitud_segundos / 3600.0)
                        * CASE longitud_hemisferio WHEN 'W' THEN -1 ELSE 1 END
                      ) STORED,

  -- El punto para ArcGIS, tambien generado. Ni un disparador de por medio: no
  -- hay forma de que el punto no corresponda a lo digitado.
  ubicacion           geography(Point,4326) GENERATED ALWAYS AS (
                        ST_SetSRID(ST_MakePoint(
                          (((longitud_grados + longitud_minutos / 60.0 + longitud_segundos / 3600.0)
                            * CASE longitud_hemisferio WHEN 'W' THEN -1 ELSE 1 END))::double precision,
                          (((latitud_grados + latitud_minutos / 60.0 + latitud_segundos / 3600.0)
                            * CASE latitud_hemisferio WHEN 'S' THEN -1 ELSE 1 END))::double precision
                        ), 4326)::geography
                      ) STORED,

  CONSTRAINT herramienta_aid_latitud_grados_rango CHECK (latitud_grados BETWEEN 0 AND 90),
  CONSTRAINT herramienta_aid_latitud_minutos_rango CHECK (latitud_minutos BETWEEN 0 AND 59),
  CONSTRAINT herramienta_aid_latitud_segundos_rango CHECK (latitud_segundos >= 0 AND latitud_segundos < 60),
  CONSTRAINT herramienta_aid_latitud_hemisferio_valido CHECK (latitud_hemisferio IN ('N', 'S')),
  CONSTRAINT herramienta_aid_longitud_grados_rango CHECK (longitud_grados BETWEEN 0 AND 180),
  CONSTRAINT herramienta_aid_longitud_minutos_rango CHECK (longitud_minutos BETWEEN 0 AND 59),
  CONSTRAINT herramienta_aid_longitud_segundos_rango CHECK (longitud_segundos >= 0 AND longitud_segundos < 60),
  CONSTRAINT herramienta_aid_longitud_hemisferio_valido CHECK (longitud_hemisferio IN ('E', 'W')),
  -- P3: las cuatro columnas de auditoria de fila MAS la bitacora de R15.
  creado_en           timestamptz NOT NULL DEFAULT now(),
  creado_por          bigint,
  modificado_en       timestamptz NOT NULL DEFAULT now(),
  modificado_por      bigint,

  CONSTRAINT herramienta_aid_codigo_unico UNIQUE (codigo),
  CONSTRAINT herramienta_aid_nombre_no_vacio CHECK (btrim(nombre) <> '')
);
COMMENT ON TABLE ai.herramienta_aid IS
  'R8, maestro 3 de 3. R13: captura georreferenciacion, aunque no sea una actividad. Es el formulario que se olvida de los seis.';

-- Valores de los atributos propios de cada tipo de herramienta.
CREATE TABLE ai.herramienta_aid_atributo (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_herramienta_aid  bigint NOT NULL REFERENCES ai.herramienta_aid(id) ON DELETE CASCADE,
  id_atributo         integer NOT NULL REFERENCES ref.atributo_herramienta_aid(id),
  valor               text,
  CONSTRAINT herramienta_aid_atributo_unico UNIQUE (id_herramienta_aid, id_atributo)
);
COMMENT ON TABLE ai.herramienta_aid_atributo IS
  'Valores de los campos propios de cada tipo de herramienta. Vacio mientras Q3 no se responda: no se sabe que campos activa cada tipo.';

-- ── Privilegios ────────────────────────────────────────────────────────────
-- R14: DELETE solo para administracion.
GRANT SELECT ON ai.personal, ai.entidad, ai.herramienta_aid, ai.herramienta_aid_atributo
  TO paid_consulta, paid_operacion, paid_administracion;
GRANT INSERT, UPDATE ON ai.personal, ai.entidad, ai.herramienta_aid, ai.herramienta_aid_atributo
  TO paid_operacion, paid_administracion;
GRANT DELETE ON ai.personal, ai.entidad, ai.herramienta_aid, ai.herramienta_aid_atributo
  TO paid_administracion;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA ai TO paid_operacion, paid_administracion;
