-- ═══════════════════════════════════════════════════════════════════════════
-- 0006 — Supertipo de actividad y sus cinco subtipos (esquema `ai`)
--
-- ⚠️ ESTE ARCHIVO ES LA RESPUESTA AL ANTI-PATRON P1.
--
-- Lo prohibido: `tipo_actividad VARCHAR` + `id_referencia_actividad BIGINT`
-- sin clave foranea. Deja huerfanos silenciosos, y un valor mal escrito
-- desvincula filas sin que nada falle.
--
-- Lo implementado: supertipo `ai.actividad` con clave foranea REAL desde cada
-- tabla hija. La disyuncion del subtipo se impone con clave foranea compuesta
-- `(id_actividad, id_tipo_actividad)` y una columna de tipo constante
-- verificada por CHECK. Consecuencias que se pueden comprobar:
--
--   - Una actividad no puede existir sin su subtipo (lo garantiza el
--     disparador de 0009, porque una clave foranea no puede exigir la
--     existencia del lado hijo).
--   - Una actividad no puede tener DOS subtipos distintos: cada tabla hija
--     fija su `id_tipo_actividad` por CHECK, y la clave foranea compuesta
--     obliga a que coincida con el de la actividad. Si la actividad es de tipo
--     1, la fila en `asistencia_humanitaria` (tipo 2) no puede existir.
--
-- Los cinco tipos se insertan AQUI, con identificadores explicitos y fijos, y
-- no en las semillas: los CHECK de las tablas hijas los citan literalmente.
-- Son estructura, no configuracion.
--
-- ⚠️ TODO(JACID): esquema derivado de PROMPT.md. Los campos propios de cada
-- subtipo son minimos a proposito: Q4 (formularios reales) sigue sin
-- responder, y no se inventan campos verosimiles. Ver docs/DECISIONES.md, D-13.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Los cinco tipos, con identificador fijo ────────────────────────────────
INSERT INTO ref.tipo_actividad (id, codigo, nombre, orden) OVERRIDING SYSTEM VALUE VALUES
  (1, 'JORNADA_APOYO',          'Jornada de Apoyo al Desarrollo', 1),
  (2, 'ASISTENCIA_HUMANITARIA', 'Asistencia Humanitaria',          2),
  (3, 'RUEDA_SERVICIOS',        'Rueda de Servicios',              3),
  (4, 'PROYECTO_SOCIAL',        'Proyecto Social',                 4),
  (5, 'CAMPANA',                'Campana institucional',           5);

-- ── Supertipo ──────────────────────────────────────────────────────────────
CREATE TABLE ai.actividad (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tipo_actividad   smallint NOT NULL REFERENCES ref.tipo_actividad(id),

  -- Q1: el algoritmo real no se conoce. Se implementa el patron observado
  -- detras de una interfaz sustituible (GeneradorCodigo, Fase 3), con unicidad
  -- por reintento sobre esta restriccion UNIQUE.
  codigo_actividad    varchar(40) NOT NULL,

  -- La unidad que registra. Es la columna sobre la que RLS decide el ambito
  -- (R6), via la ruta_jerarquica de org.unidad.
  id_unidad           bigint NOT NULL REFERENCES org.unidad(id),

  -- El clavegrama. De aqui parte U1 en la Fase 7: la extraccion propone el
  -- contenido de las once pestanas leyendo este texto, para que el usuario no
  -- vuelva a teclear a mano lo que ya escribio aqui.
  descripcion         text NOT NULL,

  -- A.2.5: fechas sin hora en DATE, no TIMESTAMP. Un TIMESTAMP invita a un
  -- componente horario espurio que desplaza el dia en los informes.
  fecha_inicio        date NOT NULL,
  fecha_fin           date,

  -- R9: la ARC siempre participa. El manual: «siempre se debe poner SI en
  -- ARC». En la interfaz aparece marcado y deshabilitado.
  participo_arc       boolean NOT NULL DEFAULT TRUE,

  -- R19: la obligatoriedad de las once pestanas NO se expresa con NOT NULL
  -- (son tablas hijas que pueden quedar vacias): se calcula aqui, por
  -- disparador (0009), y los consolidados del RAO filtran por esta columna.
  registro_completo   boolean NOT NULL DEFAULT FALSE,

  id_municipio        integer REFERENCES ref.municipio(id),
  id_estado_registro  smallint NOT NULL REFERENCES ref.estado_registro(id),

  -- ═══ R13 — Georreferenciacion ═══════════════════════════════════════════
  --
  -- Va en el SUPERTIPO y no repetida en cada subtipo. R13 exige que jornada,
  -- asistencia, rueda, proyecto y campana capturen los ocho componentes GMS:
  -- son los cinco subtipos, es decir todas las actividades. Declararlo cinco
  -- veces solo crearia cinco oportunidades de que las formulas divergieran.
  -- (El sexto formulario, herramienta AID, no es una actividad y lleva su
  -- propio bloque en ai.herramienta_aid.)
  latitud_grados      smallint NOT NULL,
  latitud_minutos     smallint NOT NULL,
  latitud_segundos    numeric(8,5) NOT NULL,
  latitud_hemisferio  char(1) NOT NULL,
  longitud_grados     smallint NOT NULL,
  longitud_minutos    smallint NOT NULL,
  longitud_segundos   numeric(8,5) NOT NULL,
  longitud_hemisferio char(1) NOT NULL,

  -- Columnas GENERADAS: no se escriben, se derivan (P6). Espejo exacto de
  -- `aDecimal()` en packages/schema/src/coordenadas.ts; una prueba de la
  -- Puerta 1 compara las dos.
  latitud_decimal     numeric(9,6) GENERATED ALWAYS AS (
                        (latitud_grados + latitud_minutos / 60.0 + latitud_segundos / 3600.0)
                        * CASE latitud_hemisferio WHEN 'S' THEN -1 ELSE 1 END
                      ) STORED,
  longitud_decimal    numeric(9,6) GENERATED ALWAYS AS (
                        (longitud_grados + longitud_minutos / 60.0 + longitud_segundos / 3600.0)
                        * CASE longitud_hemisferio WHEN 'W' THEN -1 ELSE 1 END
                      ) STORED,
  ubicacion           geography(Point,4326) GENERATED ALWAYS AS (
                        ST_SetSRID(ST_MakePoint(
                          (((longitud_grados + longitud_minutos / 60.0 + longitud_segundos / 3600.0)
                            * CASE longitud_hemisferio WHEN 'W' THEN -1 ELSE 1 END))::double precision,
                          (((latitud_grados + latitud_minutos / 60.0 + latitud_segundos / 3600.0)
                            * CASE latitud_hemisferio WHEN 'S' THEN -1 ELSE 1 END))::double precision
                        ), 4326)::geography
                      ) STORED,

  CONSTRAINT actividad_latitud_grados_rango CHECK (latitud_grados BETWEEN 0 AND 90),
  CONSTRAINT actividad_latitud_minutos_rango CHECK (latitud_minutos BETWEEN 0 AND 59),
  CONSTRAINT actividad_latitud_segundos_rango CHECK (latitud_segundos >= 0 AND latitud_segundos < 60),
  CONSTRAINT actividad_latitud_hemisferio_valido CHECK (latitud_hemisferio IN ('N', 'S')),
  CONSTRAINT actividad_longitud_grados_rango CHECK (longitud_grados BETWEEN 0 AND 180),
  CONSTRAINT actividad_longitud_minutos_rango CHECK (longitud_minutos BETWEEN 0 AND 59),
  CONSTRAINT actividad_longitud_segundos_rango CHECK (longitud_segundos >= 0 AND longitud_segundos < 60),
  CONSTRAINT actividad_longitud_hemisferio_valido CHECK (longitud_hemisferio IN ('E', 'W')),
  -- P3: las cuatro columnas de auditoria de fila MAS la bitacora de R15.
  creado_en           timestamptz NOT NULL DEFAULT now(),
  creado_por          bigint,
  modificado_en       timestamptz NOT NULL DEFAULT now(),
  modificado_por      bigint,

  CONSTRAINT actividad_codigo_unico UNIQUE (codigo_actividad),
  CONSTRAINT actividad_participo_arc_siempre_verdadero CHECK (participo_arc = TRUE),
  CONSTRAINT actividad_fechas_coherentes CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio),
  CONSTRAINT actividad_descripcion_no_vacia CHECK (btrim(descripcion) <> ''),

  -- Destino de la clave foranea compuesta de cada subtipo. Sin este UNIQUE la
  -- disyuncion de P1 no se puede declarar.
  CONSTRAINT actividad_id_y_tipo_unico UNIQUE (id, id_tipo_actividad)
);

COMMENT ON TABLE ai.actividad IS
  'Supertipo de actividad (P1). Cada subtipo apunta aqui con clave foranea compuesta (id, id_tipo_actividad), lo que hace imposible una actividad con dos subtipos. TODO(JACID): derivado de PROMPT.md.';
COMMENT ON COLUMN ai.actividad.participo_arc IS
  'R9: siempre TRUE. El CHECK lo impone; la interfaz lo muestra marcado y deshabilitado.';
COMMENT ON COLUMN ai.actividad.registro_completo IS
  'R19: calculada por disparador a partir de las once tablas hijas. Los consolidados del RAO filtran por ella.';
COMMENT ON COLUMN ai.actividad.codigo_actividad IS
  'TODO(JACID) Q1: el algoritmo real no se conoce. Patron observado <unidad>R<mes><anio><sufijo de 5>, generado detras de una interfaz sustituible.';
COMMENT ON COLUMN ai.actividad.descripcion IS
  'El clavegrama. Fuente de la extraccion U1 (Fase 7): la IA propone las once pestanas leyendo este texto.';

-- ── Subtipo 1 — ai.jornada_apoyo (Jornada de Apoyo al Desarrollo) ──
CREATE TABLE ai.jornada_apoyo (
  id_actividad      bigint PRIMARY KEY REFERENCES ai.actividad(id) ON DELETE CASCADE,

  -- Columna de tipo CONSTANTE verificada por CHECK (P1). Vale siempre 1.
  -- Junto con la clave foranea compuesta de abajo, hace imposible que esta
  -- fila cuelgue de una actividad que no sea de tipo JORNADA_APOYO.
  id_tipo_actividad smallint NOT NULL DEFAULT 1,

  fecha_ejecucion     date NOT NULL,
  lugar               varchar(250) NOT NULL,
  observaciones       text,
  creado_en         timestamptz NOT NULL DEFAULT now(),
  creado_por        bigint,
  modificado_en     timestamptz NOT NULL DEFAULT now(),
  modificado_por    bigint,

  CONSTRAINT jornada_apoyo_tipo_constante CHECK (id_tipo_actividad = 1),
  CONSTRAINT jornada_apoyo_disyuncion_subtipo
    FOREIGN KEY (id_actividad, id_tipo_actividad)
    REFERENCES ai.actividad(id, id_tipo_actividad) ON DELETE CASCADE
);
COMMENT ON TABLE ai.jornada_apoyo IS
  'Subtipo JORNADA_APOYO de ai.actividad. La disyuncion se impone por clave foranea compuesta, no por convencion (P1).';
-- ── Subtipo 2 — ai.asistencia_humanitaria (Asistencia Humanitaria) ──
CREATE TABLE ai.asistencia_humanitaria (
  id_actividad      bigint PRIMARY KEY REFERENCES ai.actividad(id) ON DELETE CASCADE,

  -- Columna de tipo CONSTANTE verificada por CHECK (P1). Vale siempre 2.
  -- Junto con la clave foranea compuesta de abajo, hace imposible que esta
  -- fila cuelgue de una actividad que no sea de tipo ASISTENCIA_HUMANITARIA.
  id_tipo_actividad smallint NOT NULL DEFAULT 2,

  id_tipo_asistencia    smallint NOT NULL REFERENCES ref.tipo_asistencia(id),
  -- R17: si la asistencia es DIRECTA, el plan operacional es obligatorio.
  -- El CHECK esta mas abajo, porque necesita conocer el id de DIRECTA.
  id_plan_operacional   smallint REFERENCES ref.plan_operacional(id),
  fecha_ejecucion       date NOT NULL,
  lugar                 varchar(250) NOT NULL,
  observaciones         text,
  creado_en         timestamptz NOT NULL DEFAULT now(),
  creado_por        bigint,
  modificado_en     timestamptz NOT NULL DEFAULT now(),
  modificado_por    bigint,

  CONSTRAINT asistencia_humanitaria_tipo_constante CHECK (id_tipo_actividad = 2),
  CONSTRAINT asistencia_humanitaria_disyuncion_subtipo
    FOREIGN KEY (id_actividad, id_tipo_actividad)
    REFERENCES ai.actividad(id, id_tipo_actividad) ON DELETE CASCADE
);
COMMENT ON TABLE ai.asistencia_humanitaria IS
  'Subtipo ASISTENCIA_HUMANITARIA de ai.actividad. La disyuncion se impone por clave foranea compuesta, no por convencion (P1).';
-- ── Subtipo 3 — ai.rueda_servicios (Rueda de Servicios) ──
CREATE TABLE ai.rueda_servicios (
  id_actividad      bigint PRIMARY KEY REFERENCES ai.actividad(id) ON DELETE CASCADE,

  -- Columna de tipo CONSTANTE verificada por CHECK (P1). Vale siempre 3.
  -- Junto con la clave foranea compuesta de abajo, hace imposible que esta
  -- fila cuelgue de una actividad que no sea de tipo RUEDA_SERVICIOS.
  id_tipo_actividad smallint NOT NULL DEFAULT 3,

  fecha_ejecucion     date NOT NULL,
  lugar               varchar(250) NOT NULL,
  observaciones       text,
  creado_en         timestamptz NOT NULL DEFAULT now(),
  creado_por        bigint,
  modificado_en     timestamptz NOT NULL DEFAULT now(),
  modificado_por    bigint,

  CONSTRAINT rueda_servicios_tipo_constante CHECK (id_tipo_actividad = 3),
  CONSTRAINT rueda_servicios_disyuncion_subtipo
    FOREIGN KEY (id_actividad, id_tipo_actividad)
    REFERENCES ai.actividad(id, id_tipo_actividad) ON DELETE CASCADE
);
COMMENT ON TABLE ai.rueda_servicios IS
  'Subtipo RUEDA_SERVICIOS de ai.actividad. La disyuncion se impone por clave foranea compuesta, no por convencion (P1).';
-- ── Subtipo 4 — ai.proyecto_social (Proyecto Social) ──
CREATE TABLE ai.proyecto_social (
  id_actividad      bigint PRIMARY KEY REFERENCES ai.actividad(id) ON DELETE CASCADE,

  -- Columna de tipo CONSTANTE verificada por CHECK (P1). Vale siempre 4.
  -- Junto con la clave foranea compuesta de abajo, hace imposible que esta
  -- fila cuelgue de una actividad que no sea de tipo PROYECTO_SOCIAL.
  id_tipo_actividad smallint NOT NULL DEFAULT 4,

  nombre_proyecto     varchar(250) NOT NULL,
  valor_total         numeric(18,2),
  -- R10: escala de OCHO tramos. El avance vigente; el historico esta en
  -- ai.proyecto_avance.
  porcentaje_avance   smallint,
  observaciones       text,
  creado_en         timestamptz NOT NULL DEFAULT now(),
  creado_por        bigint,
  modificado_en     timestamptz NOT NULL DEFAULT now(),
  modificado_por    bigint,

  CONSTRAINT proyecto_social_tipo_constante CHECK (id_tipo_actividad = 4),
  CONSTRAINT proyecto_social_disyuncion_subtipo
    FOREIGN KEY (id_actividad, id_tipo_actividad)
    REFERENCES ai.actividad(id, id_tipo_actividad) ON DELETE CASCADE
);
COMMENT ON TABLE ai.proyecto_social IS
  'Subtipo PROYECTO_SOCIAL de ai.actividad. La disyuncion se impone por clave foranea compuesta, no por convencion (P1).';
-- ── Subtipo 5 — ai.campana (Campana institucional) ──
CREATE TABLE ai.campana (
  id_actividad      bigint PRIMARY KEY REFERENCES ai.actividad(id) ON DELETE CASCADE,

  -- Columna de tipo CONSTANTE verificada por CHECK (P1). Vale siempre 5.
  -- Junto con la clave foranea compuesta de abajo, hace imposible que esta
  -- fila cuelgue de una actividad que no sea de tipo CAMPANA.
  id_tipo_actividad smallint NOT NULL DEFAULT 5,

  -- Q2: el catalogo de campanas se siembra VACIO. Hasta que JACID entregue el
  -- listado de las 17, no se puede registrar una campana, y eso es correcto:
  -- mejor no poder registrarla que registrarla contra un nombre inventado.
  id_campana_institucional smallint NOT NULL REFERENCES ref.campana_institucional(id),
  fecha_ejecucion          date NOT NULL,
  observaciones            text,
  creado_en         timestamptz NOT NULL DEFAULT now(),
  creado_por        bigint,
  modificado_en     timestamptz NOT NULL DEFAULT now(),
  modificado_por    bigint,

  CONSTRAINT campana_tipo_constante CHECK (id_tipo_actividad = 5),
  CONSTRAINT campana_disyuncion_subtipo
    FOREIGN KEY (id_actividad, id_tipo_actividad)
    REFERENCES ai.actividad(id, id_tipo_actividad) ON DELETE CASCADE
);
COMMENT ON TABLE ai.campana IS
  'Subtipo CAMPANA de ai.actividad. La disyuncion se impone por clave foranea compuesta, no por convencion (P1).';

-- ── R17 — Asistencia DIRECTA exige plan operacional ────────────────────────
--
-- Se declara aqui, despues de crear la tabla, porque el CHECK necesita el id
-- de DIRECTA en ref.tipo_asistencia, que se inserta a continuacion con
-- identificador fijo por el mismo motivo que los tipos de actividad: un CHECK
-- no puede consultar otra tabla.
INSERT INTO ref.tipo_asistencia (id, codigo, nombre, orden) OVERRIDING SYSTEM VALUE VALUES
  (1, 'DIRECTA',   'Directa',   1),
  (2, 'INDIRECTA', 'Indirecta', 2);

ALTER TABLE ai.asistencia_humanitaria
  ADD CONSTRAINT asistencia_directa_exige_plan_operacional
  CHECK (id_tipo_asistencia <> 1 OR id_plan_operacional IS NOT NULL);

COMMENT ON CONSTRAINT asistencia_directa_exige_plan_operacional ON ai.asistencia_humanitaria IS
  'R17: si tipo_asistencia = DIRECTA (id 1), el plan operacional es obligatorio. Plan San Roque II, Plan Renacer.';

-- ── R10 — El avance de un proyecto: escala de OCHO tramos ──────────────────
--
-- 10, 20, 30, 40, 50, 60, 70, 100. **NO existen 80 ni 90.** El salto del 70 al
-- 100 es deliberado: cada tramo tiene su paquete documental y no hay paquete
-- definido para esos dos.
--
-- PROMPT.md lo senala como el error mas facil de cometer en todo el proyecto:
-- un diseno previo lo cometio «normalizando» la escala a diez tramos. No se
-- completa.
ALTER TABLE ai.proyecto_social
  ADD CONSTRAINT proyecto_social_avance_escala_de_ocho_tramos
  CHECK (porcentaje_avance IS NULL OR porcentaje_avance IN (10,20,30,40,50,60,70,100));

COMMENT ON CONSTRAINT proyecto_social_avance_escala_de_ocho_tramos ON ai.proyecto_social IS
  'R10: 10,20,30,40,50,60,70,100. Los tramos 80 y 90 NO existen en la escala PAID. No completar.';

-- Historico de avances. El manual exige actualizacion mensual.
CREATE TABLE ai.proyecto_avance (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_actividad      bigint NOT NULL REFERENCES ai.proyecto_social(id_actividad) ON DELETE CASCADE,
  porcentaje_avance smallint NOT NULL,
  fecha_avance      date NOT NULL,
  observacion       text NOT NULL,
  id_usuario        bigint REFERENCES seg.usuario(id),
  creado_en         timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT proyecto_avance_escala_de_ocho_tramos
    CHECK (porcentaje_avance IN (10,20,30,40,50,60,70,100)),
  CONSTRAINT proyecto_avance_observacion_no_vacia CHECK (btrim(observacion) <> ''),
  -- Un mismo tramo no se registra dos veces para el mismo proyecto: repetir un
  -- tramo no es avanzar. La progresion (que el tramo nuevo sea mayor que el
  -- ultimo) la impone el disparador de 0009, porque exige comparar con el
  -- historico.
  CONSTRAINT proyecto_avance_tramo_no_repetido UNIQUE (id_actividad, porcentaje_avance)
);
COMMENT ON TABLE ai.proyecto_avance IS
  'R10: cada cambio de avance con fecha, observacion y usuario. El manual exige actualizacion mensual. La progresion la impone el disparador de 0009.';

-- ── R18 — COAMI, relacion cero-a-muchos ────────────────────────────────────
--
-- El manual: «si no hubo participacion NO realice seleccion». La ausencia de
-- filas es un valor legitimo, no un formulario a medio llenar. Por eso es una
-- tabla de relacion y no una columna con valor por defecto.
CREATE TABLE ai.actividad_coami (
  id_actividad bigint NOT NULL REFERENCES ai.actividad(id) ON DELETE CASCADE,
  id_coami     smallint NOT NULL REFERENCES ref.coami(id),
  creado_en    timestamptz NOT NULL DEFAULT now(),
  creado_por   bigint,
  PRIMARY KEY (id_actividad, id_coami)
);
COMMENT ON TABLE ai.actividad_coami IS
  'R18: los siete COAMI de la Reserva Naval, cero-a-muchos. Ninguno por defecto: «si no hubo participacion NO realice seleccion».';

-- ── Privilegios ────────────────────────────────────────────────────────────
-- R14: el DELETE sobre una actividad falla para todo rol que no sea
-- administracion. Es lo que comprueba la Puerta 1.
GRANT SELECT ON ai.actividad, ai.jornada_apoyo, ai.asistencia_humanitaria,
  ai.rueda_servicios, ai.proyecto_social, ai.campana, ai.proyecto_avance,
  ai.actividad_coami
  TO paid_consulta, paid_operacion, paid_administracion;
GRANT INSERT, UPDATE ON ai.actividad, ai.jornada_apoyo, ai.asistencia_humanitaria,
  ai.rueda_servicios, ai.proyecto_social, ai.campana, ai.proyecto_avance,
  ai.actividad_coami
  TO paid_operacion, paid_administracion;
GRANT DELETE ON ai.actividad, ai.jornada_apoyo, ai.asistencia_humanitaria,
  ai.rueda_servicios, ai.proyecto_social, ai.campana, ai.proyecto_avance,
  ai.actividad_coami
  TO paid_administracion;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA ai TO paid_operacion, paid_administracion;
