-- ═══════════════════════════════════════════════════════════════════════════
-- 0007 — Las once tablas hijas de una actividad (R19)
--
-- ⚠️ ESTE ARCHIVO ES LA RESPUESTA AL ANTI-PATRON P2.
--
-- El diseno auditado «declaraba nueve tablas hijas y su DDL creaba cuatro;
-- faltaba `act_poblacion_beneficiada`, la cifra que alimenta el RAO». Aqui
-- estan las ONCE, y el test de inventario de la Puerta 1 falla si falta
-- alguna, citandola por su nombre.
--
-- Orden y nombres tal como los enumera R19:
--    1 Tipo Operacion          -> ai.act_tipo_operacion
--    2 Archivos Adjuntos       -> ai.act_adjunto
--    3 Entidades Servicios     -> ai.act_entidad_servicio
--    4 Servicios Prestados     -> ai.act_servicio_prestado
--    5 Poblacion Beneficiada   -> ai.act_poblacion_beneficiada   ← la que se perdio
--    6 Entidades Apoyadas      -> ai.act_entidad_apoyada
--    7 Medios Difusion         -> ai.act_medio_difusion
--    8 Medios Utilizados       -> ai.act_medio_utilizado
--    9 Recursos Utilizados     -> ai.act_recurso_utilizado
--   10 Bienes Donados          -> ai.act_bien_donado
--   11 Resumen                 -> ai.act_resumen
--
-- La obligatoriedad de las once NO se expresa con NOT NULL: son tablas hijas
-- que pueden quedar vacias. Se calcula en `ai.actividad.registro_completo`
-- (disparador de 0009) y los consolidados del RAO filtran por el.
--
-- ⚠️ TODO(JACID) Q4: de cinco de estas pestanas no se conocen los campos
-- reales (Tipo Operacion, Entidades Servicios, Servicios Prestados, Poblacion
-- Beneficiada, Entidades Apoyadas). Los campos de abajo son los minimos que
-- las reglas permiten afirmar. NO se han inventado campos verosimiles: un
-- campo inventado que nadie llena es ruido, y uno que alguien llena con otro
-- significado es un dato falso.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1 · Tipo Operacion ─────────────────────────────────────────────────────
CREATE TABLE ai.act_tipo_operacion (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_actividad   bigint NOT NULL REFERENCES ai.actividad(id) ON DELETE CASCADE,
  id_tipo_operacion smallint NOT NULL REFERENCES ref.tipo_operacion(id),
  observacion    text,
  creado_en      timestamptz NOT NULL DEFAULT now(),
  creado_por     bigint,
  modificado_en  timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT act_tipo_operacion_unico UNIQUE (id_actividad, id_tipo_operacion)
);
COMMENT ON TABLE ai.act_tipo_operacion IS 'R19, pestana 1. TODO(JACID) Q4: formulario real desconocido.';

-- ── 2 · Archivos Adjuntos ──────────────────────────────────────────────────
--
-- R11 (cuota de 10 MB AGREGADA) y R12 (extensiones y MIME real).
--
-- El binario va a MinIO; aqui quedan ruta, metadatos y hash_sha256.
CREATE TABLE ai.act_adjunto (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_actividad         bigint NOT NULL REFERENCES ai.actividad(id) ON DELETE CASCADE,
  nombre_archivo       varchar(255) NOT NULL,
  extension            varchar(10) NOT NULL REFERENCES ref.extension_permitida(extension),
  id_categoria_adjunto smallint NOT NULL REFERENCES ref.categoria_adjunto(id),
  -- R12: el MIME que el analisis del CONTENIDO REAL devolvio, no el que
  -- declaro el navegador. Se guarda para poder auditar despues por que se
  -- acepto un archivo.
  mime_detectado       varchar(120) NOT NULL,
  peso_bytes           bigint NOT NULL,
  hash_sha256          char(64) NOT NULL,
  ruta_objeto          varchar(500) NOT NULL,
  id_fase_documental   smallint NOT NULL REFERENCES ref.fase_documental(id),

  -- R14: borrado logico. Importa para R11: la cuota suma los bytes VIGENTES,
  -- asi que un adjunto dado de baja libera su espacio sin desaparecer.
  id_estado_registro   smallint NOT NULL REFERENCES ref.estado_registro(id),

  creado_en            timestamptz NOT NULL DEFAULT now(),
  creado_por           bigint,
  modificado_en        timestamptz NOT NULL DEFAULT now(),
  modificado_por       bigint,

  -- ⚠️ NO existe aqui un `CHECK (peso_bytes <= 10485760)`. Eso es exactamente
  -- el anti-patron P5: limitaria cada archivo, no la suma, y cuarenta archivos
  -- de 9 MB pasarian. La cuota AGREGADA la impone el disparador
  -- `ai.verificar_cuota_adjuntos` de la migracion 0009.
  --
  -- Lo que si tiene sentido comprobar por fila: que el archivo no este vacio y
  -- que un solo archivo no supere ya la cuota completa, porque en ese caso no
  -- hay forma de que quepa y el disparador lo rechazaria igual.
  CONSTRAINT act_adjunto_peso_positivo CHECK (peso_bytes > 0),
  CONSTRAINT act_adjunto_peso_no_supera_cuota_completa CHECK (peso_bytes <= 10485760),
  CONSTRAINT act_adjunto_hash_es_sha256_hex CHECK (hash_sha256 ~ '^[0-9a-f]{64}$'),
  CONSTRAINT act_adjunto_extension_minuscula CHECK (extension = lower(extension)),
  -- El mismo archivo no se sube dos veces a la misma actividad. Se compara por
  -- contenido (hash), no por nombre: renombrarlo no lo convierte en otro.
  CONSTRAINT act_adjunto_sin_duplicado_por_contenido UNIQUE (id_actividad, hash_sha256)
);
COMMENT ON TABLE ai.act_adjunto IS
  'R19, pestana 2. R11: la cuota de 10 MB es AGREGADA y la impone el disparador de 0009, no un CHECK de fila (P5). R12: se guarda el MIME detectado del contenido real.';
COMMENT ON COLUMN ai.act_adjunto.id_estado_registro IS
  'R14. Relevante para R11: la cuota suma los bytes VIGENTES, asi que dar de baja un adjunto libera su espacio.';

-- ── 3 · Entidades Servicios ────────────────────────────────────────────────
CREATE TABLE ai.act_entidad_servicio (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_actividad   bigint NOT NULL REFERENCES ai.actividad(id) ON DELETE CASCADE,
  -- R8: la entidad tiene que existir antes. Clave foranea obligatoria.
  id_entidad     bigint NOT NULL REFERENCES ai.entidad(id),
  observacion    text,
  creado_en      timestamptz NOT NULL DEFAULT now(),
  creado_por     bigint,
  modificado_en  timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT act_entidad_servicio_unico UNIQUE (id_actividad, id_entidad)
);
COMMENT ON TABLE ai.act_entidad_servicio IS 'R19, pestana 3. TODO(JACID) Q4: formulario real desconocido.';

-- ── 4 · Servicios Prestados ────────────────────────────────────────────────
CREATE TABLE ai.act_servicio_prestado (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_actividad        bigint NOT NULL REFERENCES ai.actividad(id) ON DELETE CASCADE,
  id_servicio_prestado smallint NOT NULL REFERENCES ref.servicio_prestado(id),
  cantidad            integer NOT NULL,
  observacion         text,
  creado_en           timestamptz NOT NULL DEFAULT now(),
  creado_por          bigint,
  modificado_en       timestamptz NOT NULL DEFAULT now(),
  modificado_por      bigint,
  -- Las cantidades alimentan el RAO y llegan a rendiciones de cuentas. Cero es
  -- un dato ambiguo («no hubo» o «no se conto»), asi que se exige positivo: si
  -- no hubo servicio, no se registra la fila.
  CONSTRAINT act_servicio_prestado_cantidad_positiva CHECK (cantidad > 0),
  CONSTRAINT act_servicio_prestado_unico UNIQUE (id_actividad, id_servicio_prestado)
);
COMMENT ON TABLE ai.act_servicio_prestado IS 'R19, pestana 4. TODO(JACID) Q4: formulario real desconocido.';

-- ── 5 · Poblacion Beneficiada ──────────────────────────────────────────────
--
-- ⚠️ ESTA ES LA TABLA QUE EL DISENO AUDITADO DOCUMENTO Y NO IMPLEMENTO (P2).
-- Es la cifra que alimenta el RAO.
--
-- TODO(JACID) Q4/Q10: no se sabe como se desglosa la cifra (¿por sexo? ¿edad?
-- ¿grupo etnico? ¿tipo de servicio recibido?), ni si se registran datos que
-- identifiquen a personas concretas, lo que activaria la Ley 1581 de 2012.
-- Mientras no se sepa, el desglose se apoya en el catalogo `ref.grupo_poblacional`
-- —que se siembra vacio— y NO hay ninguna columna con datos personales: si
-- resultara que hacen falta, se anaden con los controles que esa ley exige, no
-- antes.
CREATE TABLE ai.act_poblacion_beneficiada (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_actividad         bigint NOT NULL REFERENCES ai.actividad(id) ON DELETE CASCADE,
  id_grupo_poblacional smallint NOT NULL REFERENCES ref.grupo_poblacional(id),
  cantidad_personas    integer NOT NULL,
  observacion          text,
  creado_en            timestamptz NOT NULL DEFAULT now(),
  creado_por           bigint,
  modificado_en        timestamptz NOT NULL DEFAULT now(),
  modificado_por       bigint,
  CONSTRAINT act_poblacion_cantidad_positiva CHECK (cantidad_personas > 0),
  CONSTRAINT act_poblacion_unica_por_grupo UNIQUE (id_actividad, id_grupo_poblacional)
);
COMMENT ON TABLE ai.act_poblacion_beneficiada IS
  'R19, pestana 5. LA TABLA QUE P2 PERDIO: es la cifra que alimenta el RAO. Sin datos personales: TODO(JACID) Q10 (Ley 1581 de 2012).';

-- ── 6 · Entidades Apoyadas ─────────────────────────────────────────────────
CREATE TABLE ai.act_entidad_apoyada (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_actividad   bigint NOT NULL REFERENCES ai.actividad(id) ON DELETE CASCADE,
  id_entidad     bigint NOT NULL REFERENCES ai.entidad(id),
  observacion    text,
  creado_en      timestamptz NOT NULL DEFAULT now(),
  creado_por     bigint,
  modificado_en  timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT act_entidad_apoyada_unica UNIQUE (id_actividad, id_entidad)
);
COMMENT ON TABLE ai.act_entidad_apoyada IS 'R19, pestana 6. TODO(JACID) Q4: formulario real desconocido.';

-- ── 7 · Medios Difusion ────────────────────────────────────────────────────
CREATE TABLE ai.act_medio_difusion (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_actividad      bigint NOT NULL REFERENCES ai.actividad(id) ON DELETE CASCADE,
  id_medio_difusion smallint NOT NULL REFERENCES ref.medio_difusion(id),
  detalle           varchar(500),
  creado_en         timestamptz NOT NULL DEFAULT now(),
  creado_por        bigint,
  modificado_en     timestamptz NOT NULL DEFAULT now(),
  modificado_por    bigint,
  CONSTRAINT act_medio_difusion_unico UNIQUE (id_actividad, id_medio_difusion)
);
COMMENT ON TABLE ai.act_medio_difusion IS 'R19, pestana 7.';

-- ── 8 · Medios Utilizados ──────────────────────────────────────────────────
CREATE TABLE ai.act_medio_utilizado (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_actividad       bigint NOT NULL REFERENCES ai.actividad(id) ON DELETE CASCADE,
  id_medio_utilizado smallint NOT NULL REFERENCES ref.medio_utilizado(id),
  cantidad           integer NOT NULL,
  detalle            varchar(500),
  creado_en          timestamptz NOT NULL DEFAULT now(),
  creado_por         bigint,
  modificado_en      timestamptz NOT NULL DEFAULT now(),
  modificado_por     bigint,
  CONSTRAINT act_medio_utilizado_cantidad_positiva CHECK (cantidad > 0),
  CONSTRAINT act_medio_utilizado_unico UNIQUE (id_actividad, id_medio_utilizado)
);
COMMENT ON TABLE ai.act_medio_utilizado IS 'R19, pestana 8.';

-- ── 9 · Recursos Utilizados ────────────────────────────────────────────────
CREATE TABLE ai.act_recurso_utilizado (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_actividad   bigint NOT NULL REFERENCES ai.actividad(id) ON DELETE CASCADE,
  id_tipo_recurso smallint NOT NULL REFERENCES ref.tipo_recurso(id),
  cantidad       numeric(18,2) NOT NULL,
  unidad_medida  varchar(40),
  valor          numeric(18,2),
  detalle        varchar(500),
  creado_en      timestamptz NOT NULL DEFAULT now(),
  creado_por     bigint,
  modificado_en  timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT act_recurso_cantidad_positiva CHECK (cantidad > 0),
  CONSTRAINT act_recurso_valor_no_negativo CHECK (valor IS NULL OR valor >= 0),
  CONSTRAINT act_recurso_unico UNIQUE (id_actividad, id_tipo_recurso)
);
COMMENT ON TABLE ai.act_recurso_utilizado IS 'R19, pestana 9.';

-- ── 10 · Bienes Donados ────────────────────────────────────────────────────
CREATE TABLE ai.act_bien_donado (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_actividad        bigint NOT NULL REFERENCES ai.actividad(id) ON DELETE CASCADE,
  id_tipo_bien_donado smallint NOT NULL REFERENCES ref.tipo_bien_donado(id),
  descripcion         varchar(500) NOT NULL,
  cantidad            numeric(18,2) NOT NULL,
  unidad_medida       varchar(40),
  valor_estimado      numeric(18,2),
  id_entidad_donante  bigint REFERENCES ai.entidad(id),
  creado_en           timestamptz NOT NULL DEFAULT now(),
  creado_por          bigint,
  modificado_en       timestamptz NOT NULL DEFAULT now(),
  modificado_por      bigint,
  CONSTRAINT act_bien_donado_cantidad_positiva CHECK (cantidad > 0),
  CONSTRAINT act_bien_donado_valor_no_negativo CHECK (valor_estimado IS NULL OR valor_estimado >= 0),
  CONSTRAINT act_bien_donado_descripcion_no_vacia CHECK (btrim(descripcion) <> '')
);
COMMENT ON TABLE ai.act_bien_donado IS
  'R19, pestana 10. Sin UNIQUE por tipo: una actividad puede donar dos bienes distintos del mismo tipo. Es tambien donde U2 (Fase 7) contrasta «120 raciones» del clavegrama contra lo registrado.';

-- ── 11 · Resumen ───────────────────────────────────────────────────────────
--
-- Uno a uno con la actividad: la clave primaria ES la actividad. No hay dos
-- resumenes de una jornada.
CREATE TABLE ai.act_resumen (
  id_actividad   bigint PRIMARY KEY REFERENCES ai.actividad(id) ON DELETE CASCADE,
  texto          text NOT NULL,
  creado_en      timestamptz NOT NULL DEFAULT now(),
  creado_por     bigint,
  modificado_en  timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT act_resumen_texto_no_vacio CHECK (btrim(texto) <> '')
);
COMMENT ON TABLE ai.act_resumen IS
  'R19, pestana 11. Uno a uno con la actividad. Es el Resumen JAD que U5 (Fase 8) podria proponer a partir de los datos ya estructurados; el humano lo reescribe.';

-- ── Privilegios ────────────────────────────────────────────────────────────
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'act_tipo_operacion','act_adjunto','act_entidad_servicio','act_servicio_prestado',
    'act_poblacion_beneficiada','act_entidad_apoyada','act_medio_difusion',
    'act_medio_utilizado','act_recurso_utilizado','act_bien_donado','act_resumen'
  ] LOOP
    EXECUTE format('GRANT SELECT ON ai.%I TO paid_consulta, paid_operacion, paid_administracion', t);
    EXECUTE format('GRANT INSERT, UPDATE ON ai.%I TO paid_operacion, paid_administracion', t);
    -- R14: DELETE solo administracion.
    EXECUTE format('GRANT DELETE ON ai.%I TO paid_administracion', t);
  END LOOP;
END
$$;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA ai TO paid_operacion, paid_administracion;
