-- ═══════════════════════════════════════════════════════════════════════════
-- 0008 — Normatividad (`doc`) y auditoria (`aud`)
--
-- R15: toda insercion, modificacion y eliminacion en `ai`, `org` y `doc` queda
-- en `aud.bitacora_cambio` con imagen anterior y posterior en JSONB, usuario,
-- unidad, sesion e IP. Se alimenta por DISPARADOR (migracion 0009), no desde
-- el servicio: un servicio se puede saltar, un disparador no.
--
-- Y es de SOLO INSERCION: nadie —ni el administrador— tiene UPDATE ni DELETE.
--
-- ⚠️ TODO(JACID): esquema derivado de PROMPT.md. Ver docs/DECISIONES.md, D-13.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── doc.normatividad ───────────────────────────────────────────────────────
--
-- R16: la normatividad solo la carga JACID; las unidades descargan. El
-- privilegio de escritura se concede unicamente a paid_administracion, y el
-- permiso funcional `NORMATIVIDAD.CARGAR` se siembra solo para los roles de
-- JACID en la Fase 2.
CREATE TABLE doc.normatividad (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tipo_normatividad  smallint NOT NULL REFERENCES ref.tipo_normatividad(id),
  codigo                varchar(60) NOT NULL,
  titulo                varchar(500) NOT NULL,
  descripcion           text,
  -- A.2.5: fecha sin hora en DATE.
  fecha_expedicion      date NOT NULL,
  fecha_vigencia_hasta  date,
  nombre_archivo        varchar(255) NOT NULL,
  extension             varchar(10) NOT NULL REFERENCES ref.extension_permitida(extension),
  peso_bytes            bigint NOT NULL,
  hash_sha256           char(64) NOT NULL,
  ruta_objeto           varchar(500) NOT NULL,
  id_estado_registro    smallint NOT NULL REFERENCES ref.estado_registro(id),
  creado_en             timestamptz NOT NULL DEFAULT now(),
  creado_por            bigint,
  modificado_en         timestamptz NOT NULL DEFAULT now(),
  modificado_por        bigint,

  CONSTRAINT normatividad_codigo_unico UNIQUE (codigo),
  CONSTRAINT normatividad_titulo_no_vacio CHECK (btrim(titulo) <> ''),
  CONSTRAINT normatividad_peso_positivo CHECK (peso_bytes > 0),
  CONSTRAINT normatividad_hash_es_sha256_hex CHECK (hash_sha256 ~ '^[0-9a-f]{64}$'),
  CONSTRAINT normatividad_vigencia_coherente
    CHECK (fecha_vigencia_hasta IS NULL OR fecha_vigencia_hasta >= fecha_expedicion)
);
COMMENT ON TABLE doc.normatividad IS
  'R16: solo JACID carga; las unidades descargan. Sin cuota agregada: R11 es por actividad, y la normatividad no pertenece a una actividad.';

-- ── aud.bitacora_cambio ────────────────────────────────────────────────────
CREATE TABLE aud.bitacora_cambio (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  esquema           varchar(20) NOT NULL,
  tabla             varchar(63) NOT NULL,
  operacion         char(1) NOT NULL,
  id_registro       bigint,

  -- R15: imagen anterior y posterior. En un INSERT la anterior es NULL; en un
  -- DELETE, la posterior. Guardar las dos es lo que distingue una bitacora de
  -- las cuatro columnas de auditoria de fila, que solo conservan el ultimo
  -- modificador y pierden la huella del anterior (P3).
  imagen_anterior   jsonb,
  imagen_posterior  jsonb,

  -- Quien, desde donde y en que sesion. Sale del contexto de R7
  -- (`current_setting('app.id_usuario', true)`), no de un parametro que el
  -- servicio pudiera olvidar pasar.
  id_usuario        bigint,
  id_unidad         bigint,
  id_sesion         text,
  direccion_ip      inet,

  instante          timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT bitacora_operacion_valida CHECK (operacion IN ('I', 'U', 'D')),
  -- Un INSERT sin imagen posterior, o un DELETE sin imagen anterior, serian
  -- filas de bitacora que no dicen nada.
  CONSTRAINT bitacora_imagenes_coherentes CHECK (
    (operacion = 'I' AND imagen_anterior IS NULL AND imagen_posterior IS NOT NULL)
    OR (operacion = 'U' AND imagen_anterior IS NOT NULL AND imagen_posterior IS NOT NULL)
    OR (operacion = 'D' AND imagen_anterior IS NOT NULL AND imagen_posterior IS NULL)
  )
);
COMMENT ON TABLE aud.bitacora_cambio IS
  'R15: solo insercion. Nadie, ni el administrador, tiene UPDATE ni DELETE. Se protege de DOS formas independientes: privilegios revocados y disparador que aborta.';

-- ── R15 — Inmutabilidad, por dos caminos independientes ────────────────────
--
-- 1) Privilegios: nadie recibe UPDATE ni DELETE.
-- 2) Disparador: aborta el UPDATE o el DELETE.
--
-- Hacen falta los dos. Los privilegios no alcanzan al superusuario ni al dueno
-- de la tabla, que los ignoran; el disparador si los detiene. Y el disparador
-- solo no bastaria como declaracion de intencion: los privilegios son lo que
-- un auditor lee.
CREATE OR REPLACE FUNCTION aud.impedir_modificacion_bitacora()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION
    'aud.bitacora_cambio es de solo insercion (R15). La operacion % esta prohibida para todos, incluido el administrador.',
    TG_OP
    USING ERRCODE = 'insufficient_privilege';
END
$$;

CREATE TRIGGER bitacora_solo_insercion
  BEFORE UPDATE OR DELETE ON aud.bitacora_cambio
  FOR EACH ROW EXECUTE FUNCTION aud.impedir_modificacion_bitacora();

-- Un TRUNCATE no dispara disparadores de fila, asi que se bloquea aparte.
CREATE OR REPLACE FUNCTION aud.impedir_truncado_bitacora()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'aud.bitacora_cambio no se puede truncar (R15).'
    USING ERRCODE = 'insufficient_privilege';
END
$$;

CREATE TRIGGER bitacora_sin_truncado
  BEFORE TRUNCATE ON aud.bitacora_cambio
  FOR EACH STATEMENT EXECUTE FUNCTION aud.impedir_truncado_bitacora();

-- ── aud.exportacion ────────────────────────────────────────────────────────
--
-- PROMPT.md Fase 3, punto 4: la exportacion XLSX/CSV queda registrada. En un
-- sistema clasificado, quien se llevo que datos y cuando es parte del
-- expediente.
CREATE TABLE aud.exportacion (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario     bigint NOT NULL,
  id_unidad      bigint NOT NULL,
  modulo         varchar(60) NOT NULL,
  formato        varchar(10) NOT NULL,
  -- Los filtros con los que se exporto: sin ellos, saber «exporto jornadas» no
  -- dice cuantas ni de quien.
  filtros        jsonb NOT NULL DEFAULT '{}'::jsonb,
  cantidad_filas integer NOT NULL,
  direccion_ip   inet,
  id_sesion      text,
  instante       timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT exportacion_formato_valido CHECK (formato IN ('XLSX', 'CSV')),
  CONSTRAINT exportacion_filas_no_negativas CHECK (cantidad_filas >= 0)
);
COMMENT ON TABLE aud.exportacion IS
  'Registro de exportaciones (Fase 3, punto 4). Quien se llevo que datos y cuando.';

-- ── Privilegios ────────────────────────────────────────────────────────────

-- doc: R16, solo JACID carga.
GRANT SELECT ON doc.normatividad TO paid_consulta, paid_operacion, paid_administracion;
GRANT INSERT, UPDATE ON doc.normatividad TO paid_administracion;
GRANT DELETE ON doc.normatividad TO paid_administracion;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA doc TO paid_administracion;

-- aud: se puede leer y anadir; NUNCA modificar ni borrar.
GRANT SELECT, INSERT ON aud.bitacora_cambio TO paid_consulta, paid_operacion, paid_administracion;
GRANT SELECT, INSERT ON aud.exportacion TO paid_consulta, paid_operacion, paid_administracion;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA aud TO paid_consulta, paid_operacion, paid_administracion;

-- R15, explicito: a nadie, ni al administrador.
REVOKE UPDATE, DELETE, TRUNCATE ON aud.bitacora_cambio
  FROM paid_consulta, paid_operacion, paid_administracion, PUBLIC;
