-- ═══════════════════════════════════════════════════════════════════════════
-- 0012 — Alianzas y convenios (R16)
--
-- Hueco detectado al implementar la Fase 2: R16 dice que «el porcentaje de
-- avance de un convenio solo lo diligencia JACID» y que «las unidades hasta
-- nivel Fuerza solo concretan alianzas; los convenios son de JACID», pero la
-- Fase 1 no creo ninguna tabla donde eso viviera. El permiso `ALIANZA.AVANCE`
-- no tenia sobre que actuar.
--
-- Una alianza NO es una actividad: no cuelga de `ai.actividad` ni tiene las
-- once pestanas. Es un acuerdo con una entidad, con su propio ciclo de vida.
--
-- ⚠️ TODO(JACID) Q13: no se sabe si el porcentaje de avance de un convenio
-- sigue la escala de OCHO TRAMOS de R10 (10..70, 100) o es un porcentaje
-- libre. R10 habla expresamente de «proyectos sociales», no de convenios, asi
-- que aplicarle la escala de ocho tramos seria una suposicion. Se admite
-- 0..100 entero y se deja la pregunta: si resulta que sigue la escala de R10,
-- el CHECK se aprieta, que es una migracion trivial. Al contrario —haber
-- apretado y tener que abrir— habria rechazado datos legitimos durante meses.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE ai.alianza (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- ALIANZA o CONVENIO. R16 reparte la atribucion segun esto, y el permiso
  -- que se exige para escribir cambia con el valor.
  id_tipo_alianza    smallint NOT NULL REFERENCES ref.tipo_alianza(id),

  codigo             varchar(60) NOT NULL,
  objeto             text NOT NULL,

  -- R8: la entidad tiene que existir antes.
  id_entidad         bigint NOT NULL REFERENCES ai.entidad(id),
  id_unidad          bigint NOT NULL REFERENCES org.unidad(id),

  -- A.2.5: fechas sin hora en DATE.
  fecha_suscripcion  date NOT NULL,
  fecha_vencimiento  date,
  valor              numeric(18,2),

  -- R16: SOLO JACID lo diligencia. Se impone en tres capas:
  --   1. el permiso `ALIANZA.AVANCE`, que solo tienen ADMINISTRADOR y
  --      FUNCIONAL_JACID en la matriz sembrada;
  --   2. el CHECK de abajo, que exige que un avance solo exista en un
  --      CONVENIO —una alianza no tiene avance que diligenciar;
  --   3. el disparador de progresion, que impide retroceder.
  porcentaje_avance  smallint,
  avance_actualizado_en timestamptz,

  id_estado_registro smallint NOT NULL REFERENCES ref.estado_registro(id),
  creado_en          timestamptz NOT NULL DEFAULT now(),
  creado_por         bigint,
  modificado_en      timestamptz NOT NULL DEFAULT now(),
  modificado_por     bigint,

  CONSTRAINT alianza_codigo_unico UNIQUE (codigo),
  CONSTRAINT alianza_objeto_no_vacio CHECK (btrim(objeto) <> ''),
  CONSTRAINT alianza_fechas_coherentes
    CHECK (fecha_vencimiento IS NULL OR fecha_vencimiento >= fecha_suscripcion),
  CONSTRAINT alianza_valor_no_negativo CHECK (valor IS NULL OR valor >= 0),
  -- TODO(JACID) Q13: ¿sigue la escala de ocho tramos de R10?
  CONSTRAINT alianza_avance_rango
    CHECK (porcentaje_avance IS NULL OR porcentaje_avance BETWEEN 0 AND 100),
  -- El avance y su fecha van juntos o no van.
  CONSTRAINT alianza_avance_con_fecha CHECK (
    (porcentaje_avance IS NULL AND avance_actualizado_en IS NULL)
    OR (porcentaje_avance IS NOT NULL AND avance_actualizado_en IS NOT NULL)
  )
);

COMMENT ON TABLE ai.alianza IS
  'R16: alianzas (las concretan las unidades hasta nivel Fuerza) y convenios (de JACID). TODO(JACID) Q13: escala del porcentaje de avance.';
COMMENT ON COLUMN ai.alianza.porcentaje_avance IS
  'R16: solo JACID lo diligencia (permiso ALIANZA.AVANCE). Solo puede existir en un CONVENIO. TODO(JACID) Q13: ¿escala de ocho tramos de R10 o porcentaje libre?';

-- R16: un avance solo tiene sentido en un CONVENIO. Es una regla entre tablas
-- (necesita `ref.tipo_alianza`), asi que va en disparador y no en CHECK.
CREATE OR REPLACE FUNCTION ai.verificar_avance_solo_en_convenio()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  tipo text;
BEGIN
  IF NEW.porcentaje_avance IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT codigo INTO tipo FROM ref.tipo_alianza WHERE id = NEW.id_tipo_alianza;
  IF tipo IS DISTINCT FROM 'CONVENIO' THEN
    RAISE EXCEPTION
      'R16: el porcentaje de avance solo se diligencia en un CONVENIO. El registro % es de tipo %.',
      NEW.codigo, COALESCE(tipo, 'desconocido')
      USING ERRCODE = 'check_violation';
  END IF;

  -- El avance no retrocede. Se aplica el mismo criterio que R10 da para
  -- proyectos, porque el motivo es el mismo: un avance que baja significa que
  -- alguien se equivoco, y sobreescribirlo en silencio pierde el dato.
  IF TG_OP = 'UPDATE'
     AND OLD.porcentaje_avance IS NOT NULL
     AND NEW.porcentaje_avance < OLD.porcentaje_avance THEN
    RAISE EXCEPTION
      'El avance del convenio % no retrocede: estaba en %%% y se intento %%%.',
      NEW.codigo, OLD.porcentaje_avance, NEW.porcentaje_avance
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END
$$;

CREATE TRIGGER alianza_avance_solo_en_convenio
  BEFORE INSERT OR UPDATE ON ai.alianza
  FOR EACH ROW EXECUTE FUNCTION ai.verificar_avance_solo_en_convenio();

-- P3: las cuatro columnas de auditoria de fila.
CREATE TRIGGER alianza_auditoria_fila
  BEFORE INSERT OR UPDATE ON ai.alianza
  FOR EACH ROW EXECUTE FUNCTION aud.fijar_columnas_auditoria();

-- R15: la bitacora.
CREATE TRIGGER alianza_bitacora
  AFTER INSERT OR UPDATE OR DELETE ON ai.alianza
  FOR EACH ROW EXECUTE FUNCTION aud.registrar_cambio();

-- R6: ambito por unidad.
ALTER TABLE ai.alianza ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai.alianza FORCE ROW LEVEL SECURITY;
CREATE POLICY alianza_ambito ON ai.alianza
  FOR ALL
  USING (seg.unidad_en_ambito(id_unidad))
  WITH CHECK (seg.unidad_en_ambito(id_unidad));

CREATE INDEX alianza_unidad_idx ON ai.alianza (id_unidad);
CREATE INDEX alianza_entidad_idx ON ai.alianza (id_entidad);
CREATE INDEX alianza_tipo_idx ON ai.alianza (id_tipo_alianza);

-- R14: DELETE solo administracion.
GRANT SELECT ON ai.alianza TO paid_consulta, paid_operacion, paid_administracion;
GRANT INSERT, UPDATE ON ai.alianza TO paid_operacion, paid_administracion;
GRANT DELETE ON ai.alianza TO paid_administracion;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA ai TO paid_operacion, paid_administracion;
