-- ═══════════════════════════════════════════════════════════════════════════
-- 0015 — Los datos generales de la jornada que pide el Manual del Usuario
--
-- Fuente: Manual del Usuario PAID (septiembre de 2022), laminas 20 y 21, el
-- formulario «Jornadas de apoyo»:
--
--   «Se debe ingresar el tipo de jornada (binacional, conjunta o estrategica)»
--   «Se debe seleccionar si hubo participacion o no de EJC y FAC (Nota:
--    siempre se debe poner SI en ARC)»
--   «Se debe seleccionar si la poblacion es afecta o no a la tropa»
--
-- Ninguno estaba en PROMPT.md, y por eso la Fase 1 no los creo. Ver
-- docs/CONTRASTE-MANUAL.md, 2.1.
--
-- POR QUE EN EL SUBTIPO Y NO EN `ai.actividad`. El manual los pide en unas
-- actividades y no en otras: EJC y FAC en jornadas y asistencias; «poblacion
-- afecta» en jornadas, asistencias y proyectos; el tipo de jornada solo en
-- jornadas. Ninguno es comun a los cinco subtipos, que es el criterio por el
-- que la georreferenciacion si va en el supertipo (0006). Cuando se construyan
-- asistencias y proyectos, cada uno lleva sus columnas.
--
-- POR QUE ADMITEN NULL. Las jornadas registradas antes de esta migracion no
-- tienen el dato, y ponerles uno seria inventarlo: «no participo el EJC» es
-- una afirmacion, no un vacio (P6, D-30). NULL significa «no se registro» y
-- asi se ve en la pantalla. El esquema de entrada los exige para toda jornada
-- NUEVA, y el formulario de correccion los pide para completar las antiguas.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── ref.tipo_jornada ──
-- Dominio cerrado (P9): «BINACIONAL» y «Binacional» no pueden ser dos
-- categorias del consolidado. El contenido se siembra en semillas/, como el
-- de los demas catalogos.
CREATE TABLE ref.tipo_jornada (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT tipo_jornada_codigo_unico UNIQUE (codigo),
  CONSTRAINT tipo_jornada_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.tipo_jornada IS
  'Manual del Usuario, lamina 20: binacional, conjunta o estrategica.';

-- P3: las cuatro columnas de auditoria de fila. 0009 las pone por bucle sobre
-- las tablas que existian entonces; una tabla posterior las declara aqui.
CREATE TRIGGER tipo_jornada_auditoria_fila
  BEFORE INSERT OR UPDATE ON ref.tipo_jornada
  FOR EACH ROW EXECUTE FUNCTION aud.fijar_columnas_auditoria();

-- Mismos privilegios que el resto de `ref` (0002): todos leen, solo
-- administracion escribe.
GRANT SELECT ON ref.tipo_jornada TO paid_consulta, paid_operacion, paid_administracion;
GRANT INSERT, UPDATE ON ref.tipo_jornada TO paid_administracion;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA ref TO paid_administracion;

-- ── Las columnas de la jornada ──
ALTER TABLE ai.jornada_apoyo
  ADD COLUMN id_tipo_jornada smallint REFERENCES ref.tipo_jornada(id),
  ADD COLUMN participo_ejc boolean,
  ADD COLUMN participo_fac boolean,
  ADD COLUMN poblacion_afecta_tropa boolean;

COMMENT ON COLUMN ai.jornada_apoyo.id_tipo_jornada IS
  'Lamina 20. NULL solo en jornadas anteriores a 0015: el esquema de entrada lo exige.';
COMMENT ON COLUMN ai.jornada_apoyo.participo_ejc IS
  'Lamina 20: participacion del Ejercito. La de la ARC es ai.actividad.participo_arc (R9, siempre TRUE).';
COMMENT ON COLUMN ai.jornada_apoyo.participo_fac IS
  'Lamina 20: participacion de la Fuerza Aerea.';
COMMENT ON COLUMN ai.jornada_apoyo.poblacion_afecta_tropa IS
  'Lamina 21: si la poblacion es afecta o no a la tropa. NULL = no se registro, que no es lo mismo que «no».';

-- Los consolidados agrupan por tipo de jornada.
CREATE INDEX jornada_apoyo_tipo_idx ON ai.jornada_apoyo (id_tipo_jornada);
