-- ═══════════════════════════════════════════════════════════════════════════
-- 0016 — La herramienta AID que pide el Manual del Usuario
--
-- Fuente: Manual del Usuario PAID (septiembre de 2022), laminas 45 y 46:
--
--   «Se debe colocar la fecha que se potencializo la herramienta y si no ha
--    sido repotenciada la fecha que se adquirio dicha herramienta.»
--   «Se debe seleccionar el estado que se encuentra la herramienta (activa o
--    inactiva), si esta inactiva informar en las observaciones porque lo esta
--    y que gestion a realizado para ponerla en funcionamiento o pendiente por
--    baja.»
--   «Se debe seleccionar el nombre del responsable de la herramienta
--    (inventario fiscal) que este a su vez debe estar inscrito en el modulo de
--    personal.»
--
-- Ver docs/CONTRASTE-MANUAL.md, 2.4, y D-35.
--
-- POR QUE ADMITEN NULL. Igual que en 0015: las herramientas registradas antes
-- no tienen el dato, y ponerles uno seria inventarlo. El esquema de entrada
-- los exige para toda herramienta nueva.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── ref.estado_herramienta_aid ──
-- «Activa o inactiva». Catalogo y no booleano: el manual ya menciona un
-- tercer estado posible («pendiente por baja») como gestion, y un dominio
-- que puede crecer no se congela en un `boolean`.
CREATE TABLE ref.estado_herramienta_aid (
  id            smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        varchar(60) NOT NULL,
  nombre        varchar(200) NOT NULL,
  descripcion   text,
  orden         smallint NOT NULL DEFAULT 0,
  activo        boolean NOT NULL DEFAULT TRUE,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  creado_por    bigint,
  modificado_en timestamptz NOT NULL DEFAULT now(),
  modificado_por bigint,
  CONSTRAINT estado_herramienta_aid_codigo_unico UNIQUE (codigo),
  CONSTRAINT estado_herramienta_aid_codigo_formato CHECK (codigo ~ '^[A-Z0-9_]+$')
);
COMMENT ON TABLE ref.estado_herramienta_aid IS
  'Manual del Usuario, lamina 46: activa o inactiva.';

CREATE TRIGGER estado_herramienta_aid_auditoria_fila
  BEFORE INSERT OR UPDATE ON ref.estado_herramienta_aid
  FOR EACH ROW EXECUTE FUNCTION aud.fijar_columnas_auditoria();

GRANT SELECT ON ref.estado_herramienta_aid TO paid_consulta, paid_operacion, paid_administracion;
GRANT INSERT, UPDATE ON ref.estado_herramienta_aid TO paid_administracion;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA ref TO paid_administracion;

-- ── Las columnas de la herramienta ──
ALTER TABLE ai.herramienta_aid
  ADD COLUMN id_estado_herramienta smallint REFERENCES ref.estado_herramienta_aid(id),
  ADD COLUMN fecha_potenciacion date,
  -- R8: el responsable tiene que existir en el maestro de personal ANTES. La
  -- clave foranea lo impone; el servicio, ademas, exige que sea visible para
  -- la unidad (RLS), porque una clave foranea se comprueba sin RLS.
  ADD COLUMN id_personal_responsable bigint REFERENCES ai.personal(id);

-- La fecha de registro era una derivacion propia —el manual no la pide— y el
-- formulario obligaba a digitarla. Pasa a ser la del dia, en la hora de
-- Colombia (A.2.5): la fecha que el manual pide es la de potenciacion.
ALTER TABLE ai.herramienta_aid
  ALTER COLUMN fecha_registro SET DEFAULT (now() AT TIME ZONE 'America/Bogota')::date;

COMMENT ON COLUMN ai.herramienta_aid.fecha_potenciacion IS
  'Lamina 46: fecha en que se potencio la herramienta o, si nunca se repotencio, en que se adquirio. NULL solo en herramientas anteriores a 0016.';
COMMENT ON COLUMN ai.herramienta_aid.id_personal_responsable IS
  'Lamina 46: responsable del inventario fiscal. R8: tiene que estar inscrito en ai.personal.';
COMMENT ON COLUMN ai.herramienta_aid.descripcion IS
  'Las observaciones del manual: codigo de inventario fiscal, fecha de adquisicion, numero de serie y, si esta inactiva, por que y que gestion se hizo.';

-- «Si esta inactiva, informar en las observaciones por que.» Regla entre
-- tablas (necesita el codigo del estado), asi que va en disparador y no en
-- CHECK, como la de avance en convenio de 0012.
CREATE OR REPLACE FUNCTION ai.verificar_herramienta_inactiva_con_motivo()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  estado text;
BEGIN
  IF NEW.id_estado_herramienta IS NULL THEN
    RETURN NEW;
  END IF;
  SELECT codigo INTO estado FROM ref.estado_herramienta_aid WHERE id = NEW.id_estado_herramienta;
  IF estado = 'INACTIVA' AND btrim(COALESCE(NEW.descripcion, '')) = '' THEN
    RAISE EXCEPTION
      'La herramienta % esta inactiva: las observaciones deben decir por que y que gestion se hizo (lamina 46).',
      NEW.codigo
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END
$$;

CREATE TRIGGER herramienta_aid_inactiva_con_motivo
  BEFORE INSERT OR UPDATE ON ai.herramienta_aid
  FOR EACH ROW EXECUTE FUNCTION ai.verificar_herramienta_inactiva_con_motivo();

CREATE INDEX herramienta_aid_estado_idx ON ai.herramienta_aid (id_estado_herramienta);
CREATE INDEX herramienta_aid_responsable_idx ON ai.herramienta_aid (id_personal_responsable);
