# Generated by Django 5.2.17 on 2026-09-30 17:12

import django.core.validators
import django.db.models.expressions
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "eliminado_en",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "nit",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]{6,12}(-[0-9])?$",
                                "NIT sin puntos, p. ej. 800123456-7.",
                            )
                        ],
                    ),
                ),
                ("nombre", models.CharField(max_length=250)),
                (
                    "nombre_normalizado",
                    models.CharField(db_index=True, editable=False, max_length=250),
                ),
                ("direccion", models.CharField(blank=True, max_length=250)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("correo", models.EmailField(blank=True, max_length=254)),
                ("contacto", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "verbose_name_plural": "entidades",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="HerramientaAid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "latitud_grados",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(90)]
                    ),
                ),
                (
                    "latitud_minutos",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(59)]
                    ),
                ),
                (
                    "latitud_segundos",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(
                                Decimal("59.99999")
                            ),
                        ],
                    ),
                ),
                (
                    "latitud_hemisferio",
                    models.CharField(
                        choices=[("N", "Norte"), ("S", "Sur")], max_length=1
                    ),
                ),
                (
                    "longitud_grados",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(180)]
                    ),
                ),
                (
                    "longitud_minutos",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(59)]
                    ),
                ),
                (
                    "longitud_segundos",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(
                                Decimal("59.99999")
                            ),
                        ],
                    ),
                ),
                (
                    "longitud_hemisferio",
                    models.CharField(
                        choices=[("W", "Oeste"), ("E", "Este")], max_length=1
                    ),
                ),
                (
                    "latitud_decimal",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(
                                latitud_hemisferio="S",
                                then=django.db.models.expressions.CombinedExpression(
                                    models.ExpressionWrapper(
                                        django.db.models.expressions.CombinedExpression(
                                            django.db.models.expressions.CombinedExpression(
                                                models.F("latitud_grados"),
                                                "+",
                                                django.db.models.expressions.CombinedExpression(
                                                    models.F("latitud_minutos"),
                                                    "/",
                                                    models.Value(Decimal("60.0")),
                                                ),
                                            ),
                                            "+",
                                            django.db.models.expressions.CombinedExpression(
                                                models.F("latitud_segundos"),
                                                "/",
                                                models.Value(Decimal("3600.0")),
                                            ),
                                        ),
                                        output_field=models.DecimalField(
                                            decimal_places=6, max_digits=12
                                        ),
                                    ),
                                    "*",
                                    models.Value(Decimal("-1")),
                                ),
                            ),
                            default=models.ExpressionWrapper(
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("latitud_grados"),
                                        "+",
                                        django.db.models.expressions.CombinedExpression(
                                            models.F("latitud_minutos"),
                                            "/",
                                            models.Value(Decimal("60.0")),
                                        ),
                                    ),
                                    "+",
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("latitud_segundos"),
                                        "/",
                                        models.Value(Decimal("3600.0")),
                                    ),
                                ),
                                output_field=models.DecimalField(
                                    decimal_places=6, max_digits=12
                                ),
                            ),
                            output_field=models.DecimalField(
                                decimal_places=6, max_digits=12
                            ),
                        ),
                        output_field=models.DecimalField(
                            decimal_places=6, max_digits=12
                        ),
                    ),
                ),
                (
                    "longitud_decimal",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(
                                longitud_hemisferio="W",
                                then=django.db.models.expressions.CombinedExpression(
                                    models.ExpressionWrapper(
                                        django.db.models.expressions.CombinedExpression(
                                            django.db.models.expressions.CombinedExpression(
                                                models.F("longitud_grados"),
                                                "+",
                                                django.db.models.expressions.CombinedExpression(
                                                    models.F("longitud_minutos"),
                                                    "/",
                                                    models.Value(Decimal("60.0")),
                                                ),
                                            ),
                                            "+",
                                            django.db.models.expressions.CombinedExpression(
                                                models.F("longitud_segundos"),
                                                "/",
                                                models.Value(Decimal("3600.0")),
                                            ),
                                        ),
                                        output_field=models.DecimalField(
                                            decimal_places=6, max_digits=12
                                        ),
                                    ),
                                    "*",
                                    models.Value(Decimal("-1")),
                                ),
                            ),
                            default=models.ExpressionWrapper(
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("longitud_grados"),
                                        "+",
                                        django.db.models.expressions.CombinedExpression(
                                            models.F("longitud_minutos"),
                                            "/",
                                            models.Value(Decimal("60.0")),
                                        ),
                                    ),
                                    "+",
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("longitud_segundos"),
                                        "/",
                                        models.Value(Decimal("3600.0")),
                                    ),
                                ),
                                output_field=models.DecimalField(
                                    decimal_places=6, max_digits=12
                                ),
                            ),
                            output_field=models.DecimalField(
                                decimal_places=6, max_digits=12
                            ),
                        ),
                        output_field=models.DecimalField(
                            decimal_places=6, max_digits=12
                        ),
                    ),
                ),
                (
                    "eliminado_en",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("codigo", models.CharField(max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=250)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_registro", models.DateField()),
                ("fecha_potenciacion", models.DateField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "herramienta AID",
                "verbose_name_plural": "herramientas AID",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Personal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "eliminado_en",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9A-Za-z-]+$", "Solo números, letras y guion."
                            )
                        ],
                    ),
                ),
                ("nombres", models.CharField(max_length=150)),
                ("apellidos", models.CharField(max_length=150)),
                ("correo", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "verbose_name_plural": "personal",
                "ordering": ["apellidos", "nombres"],
            },
        ),
    ]
