# Generated by Django 5.2.17 on 2026-09-30 17:12

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maestros", "0001_initial"),
        ("nucleo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="entidad",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="entidad",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="entidad",
            name="municipio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.municipio",
            ),
        ),
        migrations.AddField(
            model_name="entidad",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.tipoentidad"
            ),
        ),
        migrations.AddField(
            model_name="entidad",
            name="unidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.unidad"
            ),
        ),
        migrations.AddField(
            model_name="herramientaaid",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="herramientaaid",
            name="estado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.estadoherramientaaid",
            ),
        ),
        migrations.AddField(
            model_name="herramientaaid",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="herramientaaid",
            name="municipio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.municipio"
            ),
        ),
        migrations.AddField(
            model_name="herramientaaid",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.tipoherramientaaid",
            ),
        ),
        migrations.AddField(
            model_name="herramientaaid",
            name="unidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.unidad"
            ),
        ),
        migrations.AddField(
            model_name="personal",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="personal",
            name="escalafon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.escalafon",
            ),
        ),
        migrations.AddField(
            model_name="personal",
            name="grado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.grado",
            ),
        ),
        migrations.AddField(
            model_name="personal",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="personal",
            name="tipo_documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.tipodocumentoidentidad",
            ),
        ),
        migrations.AddField(
            model_name="personal",
            name="unidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.unidad"
            ),
        ),
        migrations.AddField(
            model_name="herramientaaid",
            name="responsable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="maestros.personal"
            ),
        ),
        migrations.AddConstraint(
            model_name="entidad",
            constraint=models.UniqueConstraint(
                condition=models.Q(("nit", ""), _negated=True),
                fields=("nit",),
                name="entidad_nit_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="entidad",
            constraint=models.UniqueConstraint(
                condition=models.Q(("eliminado_en__isnull", True)),
                fields=("nombre_normalizado", "municipio"),
                name="entidad_nombre_municipio_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="personal",
            constraint=models.UniqueConstraint(
                models.F("tipo_documento"),
                django.db.models.functions.text.Upper("numero_documento"),
                name="personal_documento_unico",
            ),
        ),
    ]
