# Generated by Django 5.2.17 on 2026-09-30 17:47

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maestros", "0002_initial"),
        ("nucleo", "0002_funciones_base"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="entidad",
            name="entidad_nit_unico",
            constraint=models.UniqueConstraint(
                condition=models.Q(("nit", ""), _negated=True),
                fields=("nit",),
                name="entidad_nit_unico",
                violation_error_message="Ya hay una entidad registrada con ese NIT.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="entidad",
            name="entidad_nombre_municipio_unico",
            constraint=models.UniqueConstraint(
                condition=models.Q(("eliminado_en__isnull", True)),
                fields=("nombre_normalizado", "municipio"),
                name="entidad_nombre_municipio_unico",
                violation_error_message="Ya hay una entidad con ese nombre en ese municipio.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="personal",
            name="personal_documento_unico",
            constraint=models.UniqueConstraint(
                models.F("tipo_documento"),
                django.db.models.functions.text.Upper("numero_documento"),
                name="personal_documento_unico",
                violation_error_message="Esa persona ya está registrada (mismo documento).",
            ),
        ),
    ]
