# Generated by Django 5.2.17 on 2026-09-30 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndicadorImpacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=40,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z0-9_]+$",
                                "Use mayúsculas, números y guion bajo, sin espacios ni tildes.",
                            )
                        ],
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "objetivo",
                    models.TextField(help_text="Qué impacto de largo plazo mide."),
                ),
                (
                    "formula",
                    models.TextField(help_text="Cómo se calcula, en palabras."),
                ),
                ("unidad_medida", models.CharField(max_length=60)),
                (
                    "sentido",
                    models.CharField(
                        choices=[
                            ("ASCENDENTE", "Mejor cuanto más alto"),
                            ("DESCENDENTE", "Mejor cuanto más bajo"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "linea_base",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "meta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "fuente",
                    models.CharField(
                        help_text="De dónde sale el dato.", max_length=250
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "indicador de impacto",
                "verbose_name_plural": "indicadores de impacto",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="InformeGuardado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("configuracion", models.JSONField()),
                (
                    "compartido",
                    models.BooleanField(
                        default=False,
                        help_text="Visible para todos los usuarios de la plataforma.",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "informe guardado",
                "verbose_name_plural": "informes guardados",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="MedicionIndicador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo_inicio", models.DateField()),
                ("periodo_fin", models.DateField()),
                ("valor", models.DecimalField(decimal_places=4, max_digits=18)),
                ("observaciones", models.TextField(blank=True)),
                ("registrado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "medición de indicador",
                "verbose_name_plural": "mediciones de indicadores",
                "ordering": ["indicador", "periodo_inicio"],
            },
        ),
    ]
