# Generated by Django 5.2.17 on 2026-09-30 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analitica", "0001_initial"),
        ("jornadas", "0001_initial"),
        ("nucleo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="indicadorimpacto",
            name="periodicidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.periodicidad"
            ),
        ),
        migrations.AddField(
            model_name="informeguardado",
            name="propietario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="medicionindicador",
            name="indicador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mediciones",
                to="analitica.indicadorimpacto",
            ),
        ),
        migrations.AddField(
            model_name="medicionindicador",
            name="jornada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="jornadas.jornada",
            ),
        ),
        migrations.AddField(
            model_name="medicionindicador",
            name="municipio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.municipio",
            ),
        ),
        migrations.AddField(
            model_name="medicionindicador",
            name="registrado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="medicionindicador",
            name="unidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.unidad"
            ),
        ),
        migrations.AddConstraint(
            model_name="medicionindicador",
            constraint=models.CheckConstraint(
                condition=models.Q(("periodo_fin__gte", models.F("periodo_inicio"))),
                name="medicion_periodo_coherente",
            ),
        ),
        migrations.AddConstraint(
            model_name="medicionindicador",
            constraint=models.UniqueConstraint(
                fields=("indicador", "unidad", "municipio", "periodo_inicio"),
                name="medicion_unica_por_periodo",
                nulls_distinct=False,
            ),
        ),
    ]
