# Generated by Django 5.2.17 on 2026-09-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoteImportacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "via",
                    models.CharField(
                        choices=[("API", "API"), ("ARCHIVO", "Archivo plano")],
                        max_length=10,
                    ),
                ),
                ("nombre_archivo", models.CharField(blank=True, max_length=255)),
                ("recibido_en", models.DateTimeField(auto_now_add=True)),
                ("total", models.PositiveIntegerField(default=0)),
                ("aceptados", models.PositiveIntegerField(default=0)),
                ("repetidos", models.PositiveIntegerField(default=0)),
                ("rechazados", models.PositiveIntegerField(default=0)),
                ("errores", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "lote de importación",
                "verbose_name_plural": "lotes de importación",
                "ordering": ["-recibido_en"],
            },
        ),
        migrations.CreateModel(
            name="RegistroExterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_externo", models.CharField(max_length=80)),
                ("datos", models.JSONField()),
                ("resumen_contenido", models.CharField(max_length=64)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de revisión"),
                            ("APROBADO", "Aprobado: jornada creada"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                ("posibles_duplicados", models.JSONField(default=list)),
                ("motivo_rechazo", models.TextField(blank=True)),
                ("revisado_en", models.DateTimeField(blank=True, null=True)),
                ("recibido_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "registro externo",
                "verbose_name_plural": "registros externos",
                "ordering": ["-recibido_en"],
            },
        ),
        migrations.CreateModel(
            name="SistemaExterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "alcance",
                    models.CharField(
                        choices=[
                            ("ENTREGA", "Entrega actividades a la bandeja de revisión"),
                            ("LECTURA", "Solo consulta datos maestros"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "resumen_testigo",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("prefijo_testigo", models.CharField(editable=False, max_length=8)),
                ("activo", models.BooleanField(default=True)),
                (
                    "ultimo_uso",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "sistema externo",
                "verbose_name_plural": "sistemas externos",
            },
        ),
    ]
