# Generated by Django 5.2.17 on 2026-09-30 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("integracion", "0001_initial"),
        ("jornadas", "0001_initial"),
        ("nucleo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loteimportacion",
            name="recibido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="registroexterno",
            name="jornada",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registro_externo",
                to="jornadas.jornada",
            ),
        ),
        migrations.AddField(
            model_name="registroexterno",
            name="lote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registros",
                to="integracion.loteimportacion",
            ),
        ),
        migrations.AddField(
            model_name="registroexterno",
            name="revisado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="registroexterno",
            name="unidad_propuesta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.unidad"
            ),
        ),
        migrations.AddField(
            model_name="sistemaexterno",
            name="unidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.unidad"
            ),
        ),
        migrations.AddField(
            model_name="registroexterno",
            name="sistema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="integracion.sistemaexterno",
            ),
        ),
        migrations.AddField(
            model_name="loteimportacion",
            name="sistema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="integracion.sistemaexterno",
            ),
        ),
        migrations.AddConstraint(
            model_name="registroexterno",
            constraint=models.UniqueConstraint(
                fields=("sistema", "id_externo"), name="registro_externo_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="registroexterno",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("estado", "RECHAZADO"), _negated=True),
                    models.Q(("motivo_rechazo", ""), _negated=True),
                    _connector="OR",
                ),
                name="rechazo_exige_motivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="registroexterno",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("estado", "APROBADO"), _negated=True),
                    ("jornada__isnull", False),
                    _connector="OR",
                ),
                name="aprobado_exige_jornada",
            ),
        ),
    ]
