# Generated by Django 5.2.17 on 2026-09-30 17:12

import django.core.validators
import django.db.models.expressions
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("nombre_archivo", models.CharField(max_length=255)),
                ("extension", models.CharField(max_length=10)),
                ("mime_detectado", models.CharField(max_length=120)),
                ("peso_bytes", models.PositiveBigIntegerField()),
                ("resumen_sha256", models.CharField(max_length=64)),
                ("ruta_almacen", models.CharField(editable=False, max_length=300)),
            ],
            options={
                "verbose_name": "soporte",
            },
        ),
        migrations.CreateModel(
            name="Jornada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "latitud_grados",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(90)]
                    ),
                ),
                (
                    "latitud_minutos",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(59)]
                    ),
                ),
                (
                    "latitud_segundos",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(
                                Decimal("59.99999")
                            ),
                        ],
                    ),
                ),
                (
                    "latitud_hemisferio",
                    models.CharField(
                        choices=[("N", "Norte"), ("S", "Sur")], max_length=1
                    ),
                ),
                (
                    "longitud_grados",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(180)]
                    ),
                ),
                (
                    "longitud_minutos",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(59)]
                    ),
                ),
                (
                    "longitud_segundos",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(
                                Decimal("59.99999")
                            ),
                        ],
                    ),
                ),
                (
                    "longitud_hemisferio",
                    models.CharField(
                        choices=[("W", "Oeste"), ("E", "Este")], max_length=1
                    ),
                ),
                (
                    "latitud_decimal",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(
                                latitud_hemisferio="S",
                                then=django.db.models.expressions.CombinedExpression(
                                    models.ExpressionWrapper(
                                        django.db.models.expressions.CombinedExpression(
                                            django.db.models.expressions.CombinedExpression(
                                                models.F("latitud_grados"),
                                                "+",
                                                django.db.models.expressions.CombinedExpression(
                                                    models.F("latitud_minutos"),
                                                    "/",
                                                    models.Value(Decimal("60.0")),
                                                ),
                                            ),
                                            "+",
                                            django.db.models.expressions.CombinedExpression(
                                                models.F("latitud_segundos"),
                                                "/",
                                                models.Value(Decimal("3600.0")),
                                            ),
                                        ),
                                        output_field=models.DecimalField(
                                            decimal_places=6, max_digits=12
                                        ),
                                    ),
                                    "*",
                                    models.Value(Decimal("-1")),
                                ),
                            ),
                            default=models.ExpressionWrapper(
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("latitud_grados"),
                                        "+",
                                        django.db.models.expressions.CombinedExpression(
                                            models.F("latitud_minutos"),
                                            "/",
                                            models.Value(Decimal("60.0")),
                                        ),
                                    ),
                                    "+",
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("latitud_segundos"),
                                        "/",
                                        models.Value(Decimal("3600.0")),
                                    ),
                                ),
                                output_field=models.DecimalField(
                                    decimal_places=6, max_digits=12
                                ),
                            ),
                            output_field=models.DecimalField(
                                decimal_places=6, max_digits=12
                            ),
                        ),
                        output_field=models.DecimalField(
                            decimal_places=6, max_digits=12
                        ),
                    ),
                ),
                (
                    "longitud_decimal",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(
                                longitud_hemisferio="W",
                                then=django.db.models.expressions.CombinedExpression(
                                    models.ExpressionWrapper(
                                        django.db.models.expressions.CombinedExpression(
                                            django.db.models.expressions.CombinedExpression(
                                                models.F("longitud_grados"),
                                                "+",
                                                django.db.models.expressions.CombinedExpression(
                                                    models.F("longitud_minutos"),
                                                    "/",
                                                    models.Value(Decimal("60.0")),
                                                ),
                                            ),
                                            "+",
                                            django.db.models.expressions.CombinedExpression(
                                                models.F("longitud_segundos"),
                                                "/",
                                                models.Value(Decimal("3600.0")),
                                            ),
                                        ),
                                        output_field=models.DecimalField(
                                            decimal_places=6, max_digits=12
                                        ),
                                    ),
                                    "*",
                                    models.Value(Decimal("-1")),
                                ),
                            ),
                            default=models.ExpressionWrapper(
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("longitud_grados"),
                                        "+",
                                        django.db.models.expressions.CombinedExpression(
                                            models.F("longitud_minutos"),
                                            "/",
                                            models.Value(Decimal("60.0")),
                                        ),
                                    ),
                                    "+",
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("longitud_segundos"),
                                        "/",
                                        models.Value(Decimal("3600.0")),
                                    ),
                                ),
                                output_field=models.DecimalField(
                                    decimal_places=6, max_digits=12
                                ),
                            ),
                            output_field=models.DecimalField(
                                decimal_places=6, max_digits=12
                            ),
                        ),
                        output_field=models.DecimalField(
                            decimal_places=6, max_digits=12
                        ),
                    ),
                ),
                (
                    "eliminado_en",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "codigo",
                    models.CharField(editable=False, max_length=40, unique=True),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="descripción (clavegrama)"),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "fecha_ejecucion",
                    models.DateField(verbose_name="fecha de ejecución"),
                ),
                ("lugar", models.CharField(max_length=250)),
                (
                    "participo_arc",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="participó ARC"
                    ),
                ),
                (
                    "participo_ejc",
                    models.BooleanField(verbose_name="participó Ejército"),
                ),
                (
                    "participo_fac",
                    models.BooleanField(verbose_name="participó Fuerza Aérea"),
                ),
                ("poblacion_afecta_tropa", models.BooleanField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "registro_completo",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Registrada en PAID SIGIT"),
                            ("SIGIT", "Recibida de SIGIT y aprobada por JACID"),
                        ],
                        default="MANUAL",
                        editable=False,
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_ejecucion", "-id"],
            },
        ),
        migrations.CreateModel(
            name="JornadaBienDonado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("descripcion", models.CharField(max_length=500)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=18)),
                ("unidad_medida", models.CharField(blank=True, max_length=40)),
                (
                    "valor_estimado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "bien donado",
            },
        ),
        migrations.CreateModel(
            name="JornadaEntidadApoyada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("observacion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "entidad apoyada",
            },
        ),
        migrations.CreateModel(
            name="JornadaEntidadServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("observacion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "entidad que prestó servicios",
            },
        ),
        migrations.CreateModel(
            name="JornadaMedioDifusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("detalle", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "verbose_name": "medio de difusión",
            },
        ),
        migrations.CreateModel(
            name="JornadaMedioUtilizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cantidad",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("detalle", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "verbose_name": "medio utilizado",
            },
        ),
        migrations.CreateModel(
            name="JornadaPoblacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cantidad_personas",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("observacion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "población beneficiada",
            },
        ),
        migrations.CreateModel(
            name="JornadaRecurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=18)),
                ("unidad_medida", models.CharField(blank=True, max_length=40)),
                (
                    "valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("detalle", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "verbose_name": "recurso utilizado",
            },
        ),
        migrations.CreateModel(
            name="JornadaResumen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("texto", models.TextField()),
            ],
            options={
                "verbose_name": "resumen",
            },
        ),
        migrations.CreateModel(
            name="JornadaServicioPrestado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cantidad",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("observacion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "servicio prestado",
            },
        ),
        migrations.CreateModel(
            name="JornadaTipoOperacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("observacion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "tipo de operación",
            },
        ),
    ]
