# Generated by Django 5.2.17 on 2026-09-30 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jornadas", "0001_initial"),
        ("maestros", "0001_initial"),
        ("nucleo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adjunto",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.categoriaadjunto",
            ),
        ),
        migrations.AddField(
            model_name="jornada",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="jornada",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="jornada",
            name="municipio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.municipio"
            ),
        ),
        migrations.AddField(
            model_name="jornada",
            name="tipo_jornada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.tipojornada"
            ),
        ),
        migrations.AddField(
            model_name="jornada",
            name="unidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jornadas",
                to="nucleo.unidad",
            ),
        ),
        migrations.AddField(
            model_name="adjunto",
            name="jornada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jornadas.jornada"
            ),
        ),
        migrations.AddField(
            model_name="jornadabiendonado",
            name="entidad_donante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="maestros.entidad",
            ),
        ),
        migrations.AddField(
            model_name="jornadabiendonado",
            name="jornada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jornadas.jornada"
            ),
        ),
        migrations.AddField(
            model_name="jornadabiendonado",
            name="tipo_bien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.tipobiendonado"
            ),
        ),
        migrations.AddField(
            model_name="jornadaentidadapoyada",
            name="entidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="maestros.entidad"
            ),
        ),
        migrations.AddField(
            model_name="jornadaentidadapoyada",
            name="jornada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jornadas.jornada"
            ),
        ),
        migrations.AddField(
            model_name="jornadaentidadservicio",
            name="entidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="maestros.entidad"
            ),
        ),
        migrations.AddField(
            model_name="jornadaentidadservicio",
            name="jornada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jornadas.jornada"
            ),
        ),
        migrations.AddField(
            model_name="jornadamediodifusion",
            name="jornada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jornadas.jornada"
            ),
        ),
        migrations.AddField(
            model_name="jornadamediodifusion",
            name="medio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.mediodifusion"
            ),
        ),
        migrations.AddField(
            model_name="jornadamedioutilizado",
            name="jornada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jornadas.jornada"
            ),
        ),
        migrations.AddField(
            model_name="jornadamedioutilizado",
            name="medio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.medioutilizado"
            ),
        ),
        migrations.AddField(
            model_name="jornadapoblacion",
            name="grupo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.grupopoblacional",
            ),
        ),
        migrations.AddField(
            model_name="jornadapoblacion",
            name="jornada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jornadas.jornada"
            ),
        ),
        migrations.AddField(
            model_name="jornadarecurso",
            name="jornada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jornadas.jornada"
            ),
        ),
        migrations.AddField(
            model_name="jornadarecurso",
            name="tipo_recurso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.tiporecurso"
            ),
        ),
        migrations.AddField(
            model_name="jornadaresumen",
            name="jornada",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="jornadas.jornada"
            ),
        ),
        migrations.AddField(
            model_name="jornadaservicioprestado",
            name="jornada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jornadas.jornada"
            ),
        ),
        migrations.AddField(
            model_name="jornadaservicioprestado",
            name="servicio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.servicioprestado",
            ),
        ),
        migrations.AddField(
            model_name="jornadatipooperacion",
            name="jornada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jornadas.jornada"
            ),
        ),
        migrations.AddField(
            model_name="jornadatipooperacion",
            name="tipo_operacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.tipooperacion"
            ),
        ),
        migrations.AddIndex(
            model_name="jornada",
            index=models.Index(
                fields=["unidad", "fecha_ejecucion"], name="jornada_unidad_fecha_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jornada",
            index=models.Index(
                fields=["municipio", "fecha_ejecucion"],
                name="jornada_municipio_fecha_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="jornada",
            constraint=models.CheckConstraint(
                condition=models.Q(("participo_arc", True)),
                name="jornada_participo_arc_siempre",
            ),
        ),
        migrations.AddConstraint(
            model_name="jornada",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fecha_fin__isnull", True),
                    ("fecha_fin__gte", models.F("fecha_inicio")),
                    _connector="OR",
                ),
                name="jornada_fechas_coherentes",
            ),
        ),
        migrations.AddConstraint(
            model_name="jornada",
            constraint=models.CheckConstraint(
                condition=models.Q(("fecha_ejecucion__gte", models.F("fecha_inicio"))),
                name="jornada_ejecucion_no_antes_del_inicio",
            ),
        ),
        migrations.AddConstraint(
            model_name="adjunto",
            constraint=models.UniqueConstraint(
                fields=("jornada", "resumen_sha256"),
                name="adjunto_sin_duplicado_por_contenido",
            ),
        ),
        migrations.AddConstraint(
            model_name="adjunto",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("peso_bytes__gt", 0), ("peso_bytes__lte", 10485760)
                ),
                name="adjunto_peso_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="adjunto",
            constraint=models.CheckConstraint(
                condition=models.Q(("resumen_sha256__regex", "^[0-9a-f]{64}$")),
                name="adjunto_resumen_hex",
            ),
        ),
        migrations.AddConstraint(
            model_name="jornadabiendonado",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad__gt", 0)), name="jbd_cantidad_positiva"
            ),
        ),
        migrations.AddConstraint(
            model_name="jornadabiendonado",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valor_estimado__isnull", True),
                    ("valor_estimado__gte", 0),
                    _connector="OR",
                ),
                name="jbd_valor_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="jornadaentidadapoyada",
            constraint=models.UniqueConstraint(
                fields=("jornada", "entidad"), name="jea_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="jornadaentidadservicio",
            constraint=models.UniqueConstraint(
                fields=("jornada", "entidad"), name="jes_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="jornadamediodifusion",
            constraint=models.UniqueConstraint(
                fields=("jornada", "medio"), name="jmd_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="jornadamedioutilizado",
            constraint=models.UniqueConstraint(
                fields=("jornada", "medio"), name="jmu_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="jornadamedioutilizado",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad__gt", 0)), name="jmu_cantidad_positiva"
            ),
        ),
        migrations.AddConstraint(
            model_name="jornadapoblacion",
            constraint=models.UniqueConstraint(
                fields=("jornada", "grupo"), name="jpb_unica_por_grupo"
            ),
        ),
        migrations.AddConstraint(
            model_name="jornadapoblacion",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad_personas__gt", 0)),
                name="jpb_cantidad_positiva",
            ),
        ),
        migrations.AddConstraint(
            model_name="jornadarecurso",
            constraint=models.UniqueConstraint(
                fields=("jornada", "tipo_recurso"), name="jru_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="jornadarecurso",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad__gt", 0)), name="jru_cantidad_positiva"
            ),
        ),
        migrations.AddConstraint(
            model_name="jornadarecurso",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valor__isnull", True), ("valor__gte", 0), _connector="OR"
                ),
                name="jru_valor_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="jornadaservicioprestado",
            constraint=models.UniqueConstraint(
                fields=("jornada", "servicio"), name="jsp_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="jornadaservicioprestado",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad__gt", 0)), name="jsp_cantidad_positiva"
            ),
        ),
        migrations.AddConstraint(
            model_name="jornadatipooperacion",
            constraint=models.UniqueConstraint(
                fields=("jornada", "tipo_operacion"), name="jto_unico"
            ),
        ),
    ]
