# Generated by Django 5.2.17 on 2026-09-30 17:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jornadas", "0002_initial"),
        ("maestros", "0003_mensajes_de_unicidad"),
        ("nucleo", "0002_funciones_base"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jornadabiendonado",
            name="descripcion",
            field=models.CharField(max_length=500, verbose_name="descripción"),
        ),
        migrations.AlterField(
            model_name="jornadabiendonado",
            name="entidad_donante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="maestros.entidad",
                verbose_name="entidad donante",
            ),
        ),
        migrations.AlterField(
            model_name="jornadabiendonado",
            name="tipo_bien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.tipobiendonado",
                verbose_name="tipo de bien",
            ),
        ),
        migrations.AlterField(
            model_name="jornadabiendonado",
            name="unidad_medida",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="unidad de medida"
            ),
        ),
        migrations.AlterField(
            model_name="jornadabiendonado",
            name="valor_estimado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=18,
                null=True,
                verbose_name="valor estimado (COP)",
            ),
        ),
        migrations.AlterField(
            model_name="jornadaentidadapoyada",
            name="observacion",
            field=models.TextField(blank=True, verbose_name="observación"),
        ),
        migrations.AlterField(
            model_name="jornadaentidadservicio",
            name="observacion",
            field=models.TextField(blank=True, verbose_name="observación"),
        ),
        migrations.AlterField(
            model_name="jornadamediodifusion",
            name="medio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.mediodifusion",
                verbose_name="medio",
            ),
        ),
        migrations.AlterField(
            model_name="jornadapoblacion",
            name="cantidad_personas",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="personas",
            ),
        ),
        migrations.AlterField(
            model_name="jornadapoblacion",
            name="observacion",
            field=models.TextField(blank=True, verbose_name="observación"),
        ),
        migrations.AlterField(
            model_name="jornadarecurso",
            name="tipo_recurso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.tiporecurso",
                verbose_name="tipo de recurso",
            ),
        ),
        migrations.AlterField(
            model_name="jornadarecurso",
            name="unidad_medida",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="unidad de medida"
            ),
        ),
        migrations.AlterField(
            model_name="jornadarecurso",
            name="valor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=18,
                null=True,
                verbose_name="valor (COP)",
            ),
        ),
        migrations.AlterField(
            model_name="jornadaservicioprestado",
            name="observacion",
            field=models.TextField(blank=True, verbose_name="observación"),
        ),
        migrations.AlterField(
            model_name="jornadatipooperacion",
            name="observacion",
            field=models.TextField(blank=True, verbose_name="observación"),
        ),
        migrations.AlterField(
            model_name="jornadatipooperacion",
            name="tipo_operacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.tipooperacion",
                verbose_name="tipo de operación",
            ),
        ),
    ]
